import {createServer} from 'node:http';
import {readFile,stat,mkdir,writeFile,mkdtemp,rm} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {spawn} from 'node:child_process';
import {tmpdir} from 'node:os';
import path from 'node:path';

export const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
export async function waitFor(check,label,timeout=60000){const until=Date.now()+timeout;let last;while(Date.now()<until){try{last=await check();if(last)return last;}catch(error){last=error.message;}await delay(100);}throw Error('Timeout: '+label+'; last='+JSON.stringify(last));}
export function browserExecutable(){
 const candidates=[process.env.BROWSER_EXECUTABLE,...(process.platform==='win32'?['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe']:['/usr/bin/google-chrome','/usr/bin/chromium','/usr/bin/chromium-browser'])].filter(Boolean);
 const found=candidates.find(existsSync);if(!found)throw Error('No installed Chromium browser; set BROWSER_EXECUTABLE. No automatic downloads.');return found;
}
export async function staticServer(root){
 const mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.geojson':'application/geo+json','.png':'image/png','.svg':'image/svg+xml'};
 const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');const file=path.resolve(root,'.'+decodeURIComponent(url.pathname));if(!file.startsWith(path.resolve(root)+path.sep)&&file!==path.resolve(root))throw Error('Outside root');const info=await stat(file);const target=info.isDirectory()?path.join(file,'index.html'):file;res.writeHead(200,{'Content-Type':mime[path.extname(target)]||'application/octet-stream','Cache-Control':'no-store'});res.end(await readFile(target));}catch{res.writeHead(404);res.end('Not found');}});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));return {url:'http://127.0.0.1:'+server.address().port,close:()=>new Promise(resolve=>server.close(resolve))};
}
class Page{
 constructor(socket,targetId,endpoint){this.targetId=targetId;this.endpoint=endpoint;this.closed=false;this.socket=socket;this.id=0;this.pending=new Map();this.paused=[];this.errors=[];this.console=[];this.requests=[];this.responses=[];this.failures=[];this.requestIds=new Map();socket.addEventListener('message',event=>{const value=JSON.parse(event.data);if(value.id){const waiter=this.pending.get(value.id);if(!waiter)return;this.pending.delete(value.id);clearTimeout(waiter.timer);value.error?waiter.reject(Error(JSON.stringify(value.error))):waiter.resolve(value.result);return;}const p=value.params;if(value.method==='Fetch.requestPaused')this.paused.push(p);if(value.method==='Runtime.exceptionThrown')this.errors.push(p.exceptionDetails);if(value.method==='Runtime.consoleAPICalled')this.console.push({type:p.type,text:p.args.map(a=>a.value??a.description).join(' ')});if(value.method==='Log.entryAdded')this.console.push(p.entry);if(value.method==='Network.requestWillBeSent'){this.requests.push({url:p.request.url,method:p.request.method});this.requestIds.set(p.requestId,p.request.url);}if(value.method==='Network.responseReceived')this.responses.push({url:p.response.url,status:p.response.status,mime:p.response.mimeType});if(value.method==='Network.loadingFailed')this.failures.push({url:this.requestIds.get(p.requestId),error:p.errorText,canceled:p.canceled});});}
 send(method,params={}){return new Promise((resolve,reject)=>{const id=++this.id;const timer=setTimeout(()=>{this.pending.delete(id);reject(Error('CDP timeout '+method));},60000);this.pending.set(id,{resolve,reject,timer});this.socket.send(JSON.stringify({id,method,params}));});}
 async evaluate(expression){const r=await this.send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true,userGesture:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;}
 async viewport(width,height){await this.send('Page.bringToFront');await this.send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:width<=720});await waitFor(()=>this.evaluate('innerWidth==='+width+' && matchMedia("(max-width: 720px)").matches==='+String(width<=720)),'viewport update');await delay(200);}
 async navigate(url){await this.send('Page.navigate',{url});await waitFor(()=>this.evaluate("document.readyState==='complete' && !!document.querySelector('#filter-list input') && !!document.querySelector('.tree-select')"),'app ready',90000);await this.evaluate("import('./app.js').then(async m=>{await m.frontendReady;window.qaApp=m;return true;})");await delay(250);}
 async click(selector){const box=await this.evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e)throw Error('Missing '+${JSON.stringify(selector)});e.scrollIntoView({block:'nearest',inline:'nearest'});const r=e.getBoundingClientRect();if(!r.width||!r.height)throw Error('Hidden '+${JSON.stringify(selector)});return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);await this.send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...box});await this.send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...box});await delay(150);}
 async key(key){const code={ArrowDown:40,ArrowUp:38,ArrowLeft:37,ArrowRight:39,Enter:13,Escape:27,Tab:9,' ':32}[key]||0;await this.send('Input.dispatchKeyEvent',{type:'keyDown',key,code:key===' '?'Space':key,windowsVirtualKeyCode:code,nativeVirtualKeyCode:code,...(key==='Enter'?{text:'\r',unmodifiedText:'\r'}:key===' '?{text:' ',unmodifiedText:' '}:{})});await this.send('Input.dispatchKeyEvent',{type:'keyUp',key,windowsVirtualKeyCode:code,nativeVirtualKeyCode:code});await delay(100);}
 async query(text){await this.click('#entity-search');await this.evaluate("document.querySelector('#entity-search').value=''");await this.send('Input.insertText',{text});await waitFor(()=>this.evaluate("document.querySelector('#entity-search').getAttribute('aria-expanded')==='true'"),'search open');}
 async selectQuery(text){await this.query(text);await this.key('ArrowDown');const id=await this.evaluate("document.querySelector('[role=option][aria-selected=true]').dataset.entityId");await this.key('Enter');await waitFor(()=>this.evaluate(`qaApp.selectedEntityId===${JSON.stringify(id)} && document.querySelector('#details-title').textContent!=='Nicio selecție'`),'selection');return id;}
 async screenshot(file){await mkdir(path.dirname(file),{recursive:true});const result=await this.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await writeFile(file,Buffer.from(result.data,'base64'));}
 async close(){if(this.closed)return;this.closed=true;await fetch(this.endpoint+'/json/close/'+this.targetId).catch(()=>{});this.socket.close();}
}
export async function launchBrowser(root){
 const executable=browserExecutable(),profile=await mkdtemp(path.join(tmpdir(),'atlas-browser-')),server=await staticServer(root);
 if(!path.isAbsolute(profile)||!profile.startsWith(path.join(tmpdir(),'atlas-browser-')))throw Error('Unexpected temporary profile path');
 const child=spawn(executable,['--headless=new','--remote-debugging-port=0','--remote-allow-origins=*','--no-first-run','--no-default-browser-check','--disable-dev-shm-usage','--user-data-dir='+profile,'about:blank'],{windowsHide:true,stdio:['ignore','ignore','pipe']});let stderr='';child.stderr.on('data',data=>stderr+=data);
 const port=await waitFor(async()=>{try{return Number((await readFile(path.join(profile,'DevToolsActivePort'),'utf8')).split('\n')[0]);}catch{if(child.exitCode!==null)throw Error('Browser exited '+child.exitCode+stderr);return false;}},'browser launch',20000);
 const version=await (await fetch('http://127.0.0.1:'+port+'/json/version')).json();
 const pages=[];return {server,version,executable,async page(){const target=await (await fetch('http://127.0.0.1:'+port+'/json/new?about:blank',{method:'PUT'})).json();const socket=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{socket.addEventListener('open',resolve,{once:true});socket.addEventListener('error',reject,{once:true});});const page=new Page(socket,target.id,'http://127.0.0.1:'+port);pages.push(page);for(const domain of ['Page','Runtime','Network','Log'])await page.send(domain+'.enable');return page;},async close(){for(const page of pages)await page.close();child.kill();await server.close();await delay(300);await rm(profile,{recursive:true,force:true,maxRetries:5,retryDelay:300}).catch(()=>{});}};
}
