import {formatEntityName} from '../../atlas-name-format.mjs';
import {compactTreeName} from '../../atlas-tree-labels.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {writeFile,mkdir} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {tmpdir} from 'node:os';
import {launchBrowser,waitFor,delay} from './helpers/atlas-browser.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url)),output=process.env.ATLAS_QA_OUTPUT||path.join(tmpdir(),'atlas-browser-evidence');
const entities=JSON.parse(readFileSync(path.join(root,'public/data/actual-entities.json'))).entities,nodes=JSON.parse(readFileSync(path.join(root,'public/data/actual-consolidated-tree.json'))).nodes;
const roCity=entities.find(e=>e.jurisdiction==='RO'&&e.representation.inferred_type==='municipality'&&/Ia[șş]i/i.test(e.display_name));
const roCounty=entities.find(e=>e.statistical?.classification==='NUTS'&&e.statistical?.level===3)||entities.find(e=>e.jurisdiction==='RO'&&e.representation.inferred_type==='county');
const md114=entities.find(e=>e.statistical?.code==='MD114'),md115=entities.find(e=>e.statistical?.code==='MD115'),md120=entities.find(e=>e.statistical?.code==='MD120');
const b=await launchBrowser(root),page=await b.page(),base=process.env.ATLAS_QA_URL||b.server.url;const evidence={browser:b.version.Browser,protocol:b.version['Protocol-Version'],url:base,viewports:[],screenshots:[],scenarios:[]};let share;
const shot=async(name,p=page)=>{const file=path.join(output,name+'.png');await p.screenshot(file);evidence.screenshots.push(file);};
const evalState=()=>page.evaluate("({id:qaApp.selectedEntityId,title:document.querySelector('#details-title').textContent,selected:document.querySelectorAll('.tree-select[aria-pressed=true]').length,breadcrumb:document.querySelector('.hierarchy-breadcrumb')?.textContent,hidden:document.querySelector('#selection-visibility').textContent,sheet:qaApp.atlasMobile.state.sheet,drawer:qaApp.atlasMobile.state.drawer,url:location.href})");
const subtypeInput=id=>'input[data-kind="geometry-subtype"][data-filter="'+id+'"]';
const openSubtype=async id=>{if(await page.evaluate("document.querySelector('#filters-panel').hidden"))await page.click('#filters-toggle');await page.evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(subtypeInput(id))});e.closest('details').open=true;})()`);await delay(100);};
const highlight=()=>page.evaluate("[...document.querySelectorAll('.leaflet-map-pane path')].filter(p=>p.getAttribute('stroke')==='#b54a38').length");
const bounds=async p=>p.evaluate(`(()=>{const rect=e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height,right:r.right,bottom:r.bottom};};const visible=e=>!!e&&!e.hidden&&getComputedStyle(e).visibility!=='hidden'&&e.getBoundingClientRect().height>0;return {width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,map:rect(document.querySelector('#map')),controls:visible(document.querySelector('#atlas-controls'))?rect(document.querySelector('#atlas-controls')):null,details:visible(document.querySelector('#details-panel'))?rect(document.querySelector('#details-panel')):null,trigger:visible(document.querySelector('#mobile-navigation')),attribution:rect(document.querySelector('.leaflet-control-attribution')),header:rect(document.querySelector('header')),footer:rect(document.querySelector('footer'))};})()`);
function within(r,v,label){assert.ok(r.w>0&&r.h>0,label+' dimensions');assert.ok(r.x>=-1&&r.y>=-1&&r.right<=v.width+1&&r.bottom<=v.height+1,label+' outside viewport '+JSON.stringify(r));}
async function scenario(name,fn){await test(name,{timeout:180000},async()=>{await fn();evidence.scenarios.push(name);});}
try{
 for(const [w,h] of [[1440,900],[1280,800],[900,768],[360,800],[390,844],[430,932],[390,600]])await scenario('initial layout '+w+'x'+h,async()=>{await page.viewport(w,h);if(!evidence.viewports.length)await page.navigate(base);const v=await bounds(page);evidence.viewports.push({w,h,bounds:v});assert.equal(v.scrollWidth,w,'horizontal overflow');within(v.map,v,'map');within(v.attribution,v,'attribution');if(w<=720){assert.equal(v.controls,null);assert.equal(v.details,null);assert.equal(v.trigger,true);const logicalHeight=await page.evaluate("document.querySelector('#atlas-viewport').clientHeight");assert.ok(v.map.h>=logicalHeight*.8,'map dominates effective atlas viewport');}else{within(v.controls,v,'controls');assert.equal(v.details,null,'P5.1: card hidden before first selection');assert.equal(v.trigger,false);assert.ok(v.map.x>=v.controls.right+6,'map is to right of resizable sidebar');assert.ok(v.map.w>0);}await shot('initial-'+w+'x'+h);});
 await scenario('P5.2 default roots only, independent controls, lazy navigation',async()=>{
   await page.viewport(1440,900);
   const initial=await page.evaluate("({checked:[...document.querySelectorAll('#hierarchy-tree .tree-visibility-toggle')].filter(e=>e.checked).map(e=>e.dataset.entityId).sort(),explicit:[...qaApp.visibleEntityIds].sort(),selected:qaApp.selectedEntityId,rendered:document.querySelectorAll('#hierarchy-tree .tree-select').length,details:document.querySelector('#details-panel').hidden,technical:document.querySelector('#hierarchy-tree .tree-role')})");
   const roots=['osm-r90689','osm-r58974'].sort();
   assert.deepEqual(initial.checked,roots);assert.deepEqual(initial.explicit,roots);
   assert.equal(initial.selected,null);assert.equal(initial.details,true);assert.ok(initial.rendered<100);assert.equal(initial.technical,null);
   const root=await page.evaluate("(()=>{const b=document.querySelector('.tree-branch>.tree-select'),r=b.parentElement;return{arrow:r.querySelector('details>summary')!==null,checkbox:r.querySelector('input.tree-visibility-toggle')!==null,name:b.querySelector('.tree-name').textContent};})()");
   assert.ok(root.arrow&&root.checkbox);assert.ok(root.name==='România'||root.name==='Moldova');
   await page.evaluate("(()=>{const e=document.querySelector('#hierarchy-tree .tree-disclosure');e.open=false;e.open=true;})()");
   assert.deepEqual(await page.evaluate('[...qaApp.visibleEntityIds].sort()'),roots);await shot('desktop-hierarchy-p52');
  });
  // P4 cartographic regressions explicitly enable the entities under test.
  await page.evaluate('(()=>{for(const id of '+JSON.stringify([roCity.id,roCounty.id,md114.id,md115.id,md120.id])+')qaApp.visibleEntityIds.add(id);qaApp.refreshGeometryVisibility();qaApp.atlasUrl.commit("replace");})()');
 await scenario('desktop keyboard search normalization, identifiers, grouping and no result',async()=>{
  await page.viewport(1440,900);const mdLegal=entities.find(e=>e.jurisdiction==='MD'&&e.legal?.id&&e.representation.inferred_type==='district');
  for(const [query,id] of [['Iasi',roCity.id],['Victoria',null],['Balti',null],['Bălți',null],[roCity.legal.id,roCity.id],[mdLegal.legal.id,mdLegal.id],[roCity.id.replace('osm-r',''),roCity.id],['MD120',md120.id]]){await page.query(query);const ids=await page.evaluate("[...document.querySelectorAll('[role=option]')].map(e=>e.dataset.entityId)");assert.ok(ids.length>0,query);assert.equal(new Set(ids).size,ids.length);if(id)assert.ok(ids.includes(id),query+' missing real ID');await page.key('ArrowDown');assert.equal(await page.evaluate("document.activeElement.id"),'entity-search');assert.equal(await page.evaluate("document.querySelectorAll('[role=option][aria-selected=true]').length"),1);await page.key('ArrowDown');await page.key('ArrowUp');const active=await page.evaluate("document.querySelector('#entity-search').getAttribute('aria-activedescendant')");assert.ok(await page.evaluate(`!!document.getElementById(${JSON.stringify(active)})`));}
  await page.query('Victoria');assert.deepEqual(await page.evaluate("[...document.querySelectorAll('.search-group-heading')].map(e=>e.textContent)"),['România','Moldova']);await shot('desktop-search');await page.key('Escape');assert.equal(await page.evaluate("document.querySelector('#search-results').hidden"),true);await page.query('zzzz-imposibil-987654');assert.equal(await page.evaluate("document.querySelectorAll('[role=option]').length"),0);assert.equal(await page.evaluate("document.querySelector('#search-status').textContent"),'Nicio entitate găsită.');await page.key('Enter');assert.equal((await evalState()).id,null);await page.key('Escape');
 });
 await scenario('desktop search selection synchronizes map tree breadcrumb and details',async()=>{assert.equal(await page.selectQuery(roCity.id),roCity.id);await waitFor(highlight,'selected polygon rendered');const s=await evalState();assert.equal(s.selected,1);assert.ok(s.breadcrumb.includes(formatEntityName(roCity.display_name)));assert.equal(s.title,formatEntityName(roCity.display_name));assert.ok(new URL(s.url).searchParams.get('e')===roCity.id);assert.deepEqual(await page.evaluate("[...document.querySelectorAll('#details-body .details-section h3')].map(e=>e.textContent)"),['Identitate oficială','Rol statistic','Reprezentare cartografică']);await shot('desktop-selected');for(const [w,h] of [[1280,800],[900,768]]){await page.viewport(w,h);const v=await bounds(page);within(v.details,v,'selected details');within(v.attribution,v,'attribution');await shot('selected-'+w+'x'+h);}await page.viewport(1440,900);});
 await scenario('filter child hidden selection, parent mixed, reenable highlight and jurisdictions persist',async()=>{await openSubtype('ro.municipalities');await page.click(subtypeInput('ro.municipalities'));await waitFor(async()=>await highlight()===0,'hidden highlight removed');const s=await evalState();assert.equal(s.id,roCity.id);assert.equal(s.selected,1);assert.ok(s.breadcrumb);assert.match(s.hidden,/ascuns/i);assert.equal(await page.evaluate("document.querySelector('input[data-kind=geometry-class][data-filter=local_uat]').indeterminate"),true);await page.click('#layer-ro');await page.click('#layer-ro');assert.equal(await page.evaluate("document.querySelector('input[data-filter=\"ro.municipalities\"]').checked"),false);await page.click(subtypeInput('ro.municipalities'));await waitFor(highlight,'highlight restored');await shot('desktop-filters');const requestCount=page.requests.filter(r=>/actual-entities|consolidated-tree/.test(r.url)).length;await page.click('#layer-md');await page.click('#layer-md');assert.equal(page.requests.filter(r=>/actual-entities|consolidated-tree/.test(r.url)).length,requestCount);});
 await scenario('real all-uppercase place names render consistently in search, tree, breadcrumb and details',async()=>{
  const target=entities.find(e=>e.jurisdiction==='RO'&&e.display_name!==formatEntityName(e.display_name)&&e.representation?.osm_relation_id!=null);
  assert.ok(target,'an all-caps entity exists in the released index');
  const formatted=formatEntityName(target.display_name);
  assert.notEqual(target.display_name,formatted);
  assert.equal(await page.selectQuery(target.id),target.id);
  const state=await evalState();
  assert.equal(state.title,formatted);
  assert.ok(state.breadcrumb.includes(formatted));
  const treeLabel=await page.evaluate(`document.querySelector('.tree-select[data-entity-id="${target.id}"]').textContent`);
  assert.ok(treeLabel.startsWith(compactTreeName({display_name:target.display_name,parent_id:target.hierarchy.consolidated_parent_id,jurisdiction:target.jurisdiction})));
  await page.query(target.id);
  const searchLabel=await page.evaluate("document.querySelector('[role=option] b').textContent");
  assert.equal(searchLabel,formatted);
  await page.key('Escape');
 });
 await scenario('P5.2 checkbox remains checked under global filtering',async()=>{
   await page.selectQuery(roCity.id);
   const q='.tree-visibility-toggle[data-entity-id="'+roCity.id+'"]';
   assert.equal(await page.evaluate('document.querySelector('+JSON.stringify(q)+').checked'),true);
   await openSubtype('ro.municipalities');await page.click(subtypeInput('ro.municipalities'));
   assert.equal(await page.evaluate('document.querySelector('+JSON.stringify(q)+').checked'),true);
   assert.match((await evalState()).hidden,/ascuns/i);
   assert.equal(await page.evaluate('document.querySelector('+JSON.stringify(q)+').closest(".tree-node").classList.contains("tree-geometry-hidden")'),true);
   await page.click(subtypeInput('ro.municipalities'));
   assert.equal(await page.evaluate('document.querySelector('+JSON.stringify(q)+').closest(".tree-node").classList.contains("tree-geometry-hidden")'),false);
  });
 await scenario('parent and Toate/Niciuna native checkboxes keep statistical controls independent',async()=>{const parent='input[data-kind=geometry-class][data-filter=regional]';const stat=await page.evaluate("[...qaApp.activeStatisticalLevels]");await page.click(parent);assert.equal(await page.evaluate("document.querySelector('input[data-filter=regional]').checked"),false);await page.click(parent);assert.equal(await page.evaluate("document.querySelector('input[data-filter=regional]').checked"),true);await page.click('button[aria-label="Niciuna — Tipuri administrative"]');assert.equal(await page.evaluate("qaApp.activeGeometryClasses.has('local_uat')"),false);await page.click('button[aria-label="Toate — Tipuri administrative"]');assert.deepEqual(await page.evaluate("[...qaApp.activeStatisticalLevels]"),stat);});
 await scenario('real tree disclosure lazy depth five and selected scroll',async()=>{for(const jurisdiction of ['RO','MD']){const leaf=nodes.find(n=>n.jurisdiction===jurisdiction&&n.depth===5&&entities.find(e=>e.id===n.id)?.legal?.id)||nodes.find(n=>n.jurisdiction===jurisdiction&&n.depth===5);const by=new Map(nodes.map(n=>[n.id,n])),chain=[];let n=leaf;while(n){chain.unshift(n.id);n=by.get(n.parent_id);}await page.click('#details-close');for(const id of chain.slice(0,-1)){const selector='.tree-select[data-entity-id="'+id+'"]';await page.evaluate(`(()=>{const row=document.querySelector(${JSON.stringify(selector)}).parentElement;const disclosure=row.querySelector(':scope > details');if(!disclosure.open)disclosure.querySelector('summary').click();})()`);await delay(60);}await page.click('.tree-select[data-entity-id="'+leaf.id+'"]');await waitFor(()=>page.evaluate(`qaApp.selectedEntityId===${JSON.stringify(leaf.id)}`),'tree selection');assert.equal((await evalState()).selected,1);assert.equal(await page.evaluate(`document.querySelectorAll('.tree-select[data-entity-id="${leaf.id}"]').length`),1);assert.ok(await page.evaluate(`(()=>{const t=document.querySelector('#hierarchy-tree').getBoundingClientRect(),r=document.querySelector('.tree-select[data-entity-id="${leaf.id}"]').getBoundingClientRect();return r.top>=t.top-1&&r.bottom<=t.bottom+1;})()`));}});
 await scenario('coalesced county MD114 and MD115 single search/node/provenance',async()=>{for(const entity of [roCounty,md114,md115]){await page.query(entity.id);assert.equal(await page.evaluate("document.querySelectorAll('[role=option]').length"),1);await page.key('ArrowDown');await page.key('Enter');await waitFor(()=>page.evaluate(`qaApp.selectedEntityId===${JSON.stringify(entity.id)}`),'coalesced selection');assert.equal(await page.evaluate(`document.querySelectorAll('.tree-select[data-entity-id="${entity.id}"]').length`),1);assert.match(await page.evaluate("document.querySelector('#details-body').textContent"),/Geometrie administrativă reutilizată/i);}});
 await scenario('P5.2 statistical/coalesced rows hide codes but detail retains evidence',async()=>{
   for(const [entity,kind] of [[roCounty,'tree-coalesced'],[md114,'tree-coalesced'],[md120,'tree-statistical-only']]){
    await page.selectQuery(entity.id);
    const q='.tree-select[data-entity-id="'+entity.id+'"]';
    const state=await page.evaluate('(()=>{const row=document.querySelector('+JSON.stringify(q)+');return{name:row.querySelector(".tree-name").textContent,role:row.querySelector(".tree-role"),aria:row.getAttribute("aria-label"),cls:row.parentElement.className,count:document.querySelectorAll('+JSON.stringify(q)+').length};})()');
    assert.equal(state.count,1);assert.equal(state.name,compactTreeName({display_name:entity.display_name,parent_id:entity.hierarchy.consolidated_parent_id,jurisdiction:entity.jurisdiction}));
    assert.equal(state.role,null);assert.ok(state.aria.includes(state.name));assert.ok(state.cls.includes(kind));
    assert.match(await page.evaluate("document.querySelector('#details-body').textContent"),/statistic|Geometrie administrativă|Limită statistică/i);
   }
  });
 await scenario('statistical levels expose complete statistical layers without duplicate coalesced geometry',async()=>{
  await page.selectQuery(roCounty.id);await waitFor(highlight,'county highlighted before statistical-only view');if(await page.evaluate("document.querySelector('#filters-panel').hidden"))await page.click('#filters-toggle');
  assert.match(await page.evaluate("document.querySelector('#filter-list').textContent"),/48 entități · 44 reutilizate · 4 separate/);
  const level3='input[data-kind=statistical][data-filter="3"]';
  await page.click('button[aria-label="Niciuna — Tipuri administrative"]');
  await waitFor(highlight,'coalesced county remains visible through statistical level');
  assert.equal(await page.evaluate("document.querySelector('input[data-kind=geometry-class][data-filter=regional]').checked"),false);
  assert.equal(await page.evaluate("document.querySelector('input[data-filter=\"ro.counties\"]').checked"),false);
  await page.click(level3);await waitFor(async()=>await highlight()===0,'both administrative and statistical roles off hide county');
  assert.match((await evalState()).hidden,/ascuns/i);
  await page.click('button[aria-label="Toate — Tipuri administrative"]');await waitFor(highlight,'administrative role independently restores county');
  await page.click(level3);await waitFor(highlight,'statistical role restored without duplicate geometry');
  assert.equal(await page.evaluate("document.querySelectorAll('.leaflet-interactive').length>0"),true);
 });
 await scenario('statistical-only MD120 official identity and hidden statistical geometry',async()=>{assert.equal(await page.selectQuery('MD120'),md120.id);await waitFor(highlight,'MD120 polygon');const text=await page.evaluate("document.querySelector('#details-body').textContent");assert.match(text,/MD120/);assert.match(text,/MD121/);assert.match(text,/evidence OSM/);assert.match(text,/Limită statistică separată/);if(await page.evaluate("document.querySelector('#filters-panel').hidden"))await page.click('#filters-toggle');await page.click('input[data-kind=statistical][data-filter="3"]');await waitFor(async()=>await highlight()===0,'level hides selected');assert.equal((await evalState()).id,md120.id);assert.match((await evalState()).hidden,/ascuns/i);await page.click('input[data-kind=statistical][data-filter="3"]');await waitFor(highlight,'level restore');await page.click('input[data-kind=separate-statistical]');await waitFor(async()=>await highlight()===0,'separate hides selected');await page.click('input[data-kind=separate-statistical]');await waitFor(highlight,'separate restore');const pane=await page.evaluate("(()=>{const stat=document.querySelector('.leaflet-statistical-boundaries-pane'),overlay=document.querySelector('.leaflet-overlay-pane');return {exists:!!stat,z:Number(getComputedStyle(stat).zIndex),overlayZ:Number(getComputedStyle(overlay).zIndex),selected:!!stat.querySelector('path[stroke=\\\"#b54a38\\\"]')};})()");assert.equal(pane.exists,true);assert.ok(pane.z>pane.overlayZ);assert.equal(pane.selected,true);});
 await scenario('legend and provenance accessible on demand, read-only',async()=>{const url=await page.evaluate('location.href');await page.click('#info-toggle');assert.equal(await page.evaluate("document.querySelector('#atlas-info-dialog').open"),true);assert.equal(await page.evaluate('document.activeElement.id'),'info-close');await page.click('#atlas-legend summary');await page.click('#global-provenance summary');assert.equal(await page.evaluate("document.querySelectorAll('#atlas-legend .legend-swatch').length"),8);assert.equal(await page.evaluate("document.querySelectorAll('#atlas-legend input').length"),0);assert.equal(await page.evaluate('location.href'),url);assert.match(await page.evaluate("document.querySelector('#global-provenance').textContent"),/actual-v1.2.0/);assert.ok(await page.evaluate("(()=>{const rows=document.querySelector('#global-provenance>dl').getBoundingClientRect(),link=document.querySelector('#global-provenance>a').getBoundingClientRect();return link.top>=rows.bottom;})()"),'release link overlaps metadata');await shot('legend-provenance');await page.click('#info-close');assert.equal(await page.evaluate("document.querySelector('#atlas-info-dialog').open"),false);assert.equal(await page.evaluate('document.activeElement.id'),'info-toggle');});
 await scenario('real map polygon click pan zoom scale tiles and URL',async()=>{await page.click('#details-close');await page.click('.leaflet-control-zoom-out');await delay(500);const point=await page.evaluate("(()=>{const e=[...document.querySelectorAll('.leaflet-interactive')].find(e=>{const r=e.getBoundingClientRect();return r.width>30&&r.height>30&&r.left>330&&r.right<1090&&r.top>90&&r.bottom<800});if(!e)return null;const r=e.getBoundingClientRect();return {x:r.left+r.width/2,y:r.top+r.height/2};})()");assert.ok(point,'visible polygon');await page.send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...point});await page.send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...point});await waitFor(()=>page.evaluate('!!qaApp.selectedEntityId'),'map polygon click selected');assert.equal((await evalState()).selected,1);await page.click('.leaflet-control-zoom-in');await waitFor(()=>page.evaluate("!document.querySelector('.leaflet-zoom-anim,.leaflet-pan-anim')"),'map animation settled');await page.evaluate("document.querySelector('#map').focus()");const previous=await page.evaluate("qaApp.captureUrlState().viewport");await page.key('ArrowRight');await waitFor(async()=>JSON.stringify(await page.evaluate("qaApp.captureUrlState().viewport"))!==JSON.stringify(previous),'keyboard pan updates viewport');assert.ok(await page.evaluate("document.querySelector('.leaflet-control-scale-line').textContent.length>0"));assert.ok(page.responses.some(r=>r.url.includes('tile.openstreetmap.org')&&r.status===200));});
 await scenario('complex share URL restores hidden selection viewport filters tree in new context',async()=>{await page.selectQuery(roCity.id);await openSubtype('ro.municipalities');await page.click(subtypeInput('ro.municipalities'));await openSubtype('md.towns');await page.click(subtypeInput('md.towns'));await delay(500);await page.click('#copy-link');assert.match(await page.evaluate("document.querySelector('#share-status').textContent"),/Link copiat|Copiază URL/);share=await page.evaluate('location.href');const before=await page.evaluate("JSON.stringify(qaApp.captureUrlState(),(k,v)=>v instanceof Set?[...v].sort():['lat','lon'].includes(k)?Number(v.toFixed(5)):v)");const restored=await b.page();await restored.viewport(1440,900);await restored.navigate(share);assert.equal(await restored.evaluate('qaApp.selectedEntityId'),roCity.id);assert.equal(await restored.evaluate("qaApp.activeGeometrySubtypes.has('ro.municipalities')"),false);assert.equal(await restored.evaluate("document.querySelectorAll('.tree-select[aria-pressed=true]').length"),1);assert.match(await restored.evaluate("document.querySelector('#selection-visibility').textContent"),/ascuns/i);assert.equal(await restored.evaluate("JSON.stringify(qaApp.captureUrlState(),(k,v)=>v instanceof Set?[...v].sort():['lat','lon'].includes(k)?Number(v.toFixed(5)):v)"),before);await restored.close();});
 await scenario('real Back Forward selection filter and viewport without history loop',async()=>{await page.selectQuery(md115.id);await page.selectQuery(md114.id);await waitFor(()=>page.evaluate("!document.querySelector('.leaflet-zoom-anim,.leaflet-pan-anim')"),'history zoom settled');const original=await page.evaluate("qaApp.captureUrlState().viewport");await openSubtype('md.rural_uat');const ruralBefore=await page.evaluate("document.querySelector('input[data-filter=\"md.rural_uat\"]').checked");await page.click(subtypeInput('md.rural_uat'));await page.evaluate("document.querySelector('#map').focus()");await page.key('ArrowLeft');await waitFor(async()=>JSON.stringify(await page.evaluate("qaApp.captureUrlState().viewport"))!==JSON.stringify(original),'history pan');await delay(400);await page.evaluate('history.back()');await waitFor(()=>page.evaluate("qaApp.selectedEntityId==='"+md114.id+"' && document.querySelector('input[data-filter=\"md.rural_uat\"]').checked==="+ruralBefore+" && !qaApp.atlasUrl.isRestoring"),'Back restores B before filter and pan');const viewport=await page.evaluate("qaApp.captureUrlState().viewport");assert.ok(Math.abs(viewport.lat-original.lat)<.00001&&Math.abs(viewport.lon-original.lon)<.00001);await page.evaluate('history.back()');await waitFor(()=>page.evaluate("qaApp.selectedEntityId==='"+md115.id+"' && !qaApp.atlasUrl.isRestoring"),'Back selects A');await page.evaluate('history.forward()');await waitFor(()=>page.evaluate("qaApp.selectedEntityId==='"+md114.id+"' && !qaApp.atlasUrl.isRestoring"),'Forward selects B');const length=await page.evaluate('history.length');await delay(700);assert.equal(await page.evaluate('history.length'),length);});
 await scenario('P3.3 malformed public tree fails closed before map, selection and URL wiring',async()=>{
  const p=await b.page();
  try{
   await p.viewport(1280,800);
   await p.send('Fetch.enable',{patterns:[{urlPattern:'*actual-consolidated-tree.json*',requestStage:'Request'}]});
   await p.send('Page.navigate',{url:base});
   const paused=await waitFor(()=>p.paused.find(item=>item.request.url.includes('actual-consolidated-tree.json')),'intercept P3.3 hierarchy');
   const damaged=JSON.parse(readFileSync(path.join(root,'public/data/actual-consolidated-tree.json'),'utf8'));
   // Same count/roots; corrupt semantic identity rather than transport or JSON syntax.
   damaged.nodes.find(n=>n.parent_id!==null).display_name='IDENTITATE CORUPTĂ';
   const payload=Buffer.from(JSON.stringify(damaged)).toString('base64');
   await p.send('Fetch.fulfillRequest',{requestId:paused.requestId,responseCode:200,responseHeaders:[{name:'Content-Type',value:'application/json'}],body:payload});
   await p.send('Fetch.disable');
   await waitFor(()=>p.evaluate("document.querySelector('#hierarchy-error')?.textContent.includes('indisponibilă')"),'hierarchy rejected');
   const status=await p.evaluate("({nodes:[...document.querySelectorAll('#hierarchy-tree .tree-select')].length,error:document.querySelector('#hierarchy-error').textContent,results:document.querySelector('#entity-search')!=null})");
   assert.equal(status.nodes,0,'fail closed: corrupt public hierarchy must never populate tree');
   assert.match(status.error,/indisponibilă/);
   assert.equal(status.results,true,'index/search can remain loaded without invalid hierarchy');
  }finally{await p.close();}
 });
 await scenario('invalid duplicate URL canonicalizes safely in fresh browser context',async()=>{const p=await b.page();await p.viewport(1280,800);await p.navigate(base+'?v=1&e=invalid&e=other&lat=oops&lon=26&z=6&f=invalid&f=invalid&t=invalid');const query=await p.evaluate('location.search');assert.ok(!query.includes('invalid')&&!query.includes('oops'));assert.equal(await p.evaluate('qaApp.selectedEntityId'),null);assert.equal(p.errors.length,0);await p.close();});
 await scenario('mobile drawer keyboard Escape priority persistence and bounds',async()=>{await page.evaluate('qaApp.atlasUrl.whenIdle()');if(!await page.evaluate("document.querySelector('#filters-panel').hidden"))await page.click('#filters-close');await page.viewport(390,844);await page.click('#details-close');await page.evaluate("document.querySelector('#mobile-navigation').focus()");await page.key('Enter');assert.equal(await page.evaluate('document.activeElement.id'),'entity-search');const v=await bounds(page);within(v.controls,v,'drawer');await page.query('Victoria');await page.key('Escape');assert.equal(await page.evaluate('qaApp.atlasMobile.state.drawer'),true);await page.key('Escape');assert.equal(await page.evaluate('qaApp.atlasMobile.state.drawer'),false);assert.equal(await page.evaluate('document.activeElement.id'),'mobile-navigation');await page.click('#mobile-navigation');await shot('mobile-drawer');const openBefore=await page.evaluate("[...document.querySelectorAll('#hierarchy-tree details[open]')].map(e=>e.parentElement.querySelector('.tree-select').dataset.entityId)");await page.click('#drawer-close');await page.click('#mobile-navigation');assert.deepEqual(await page.evaluate("[...document.querySelectorAll('#hierarchy-tree details[open]')].map(e=>e.parentElement.querySelector('.tree-select').dataset.entityId)"),openBefore);await page.send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,x:385,y:400});await page.send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,x:385,y:400});await delay(150);assert.equal(await page.evaluate('qaApp.atlasMobile.state.drawer'),false);});
 await scenario('mobile search peek expanded collapse hidden geometry and short viewport',async()=>{await page.click('#mobile-navigation');await openSubtype('ro.municipalities');if(!await page.evaluate("document.querySelector('input[data-filter=\"ro.municipalities\"]').checked"))await page.click(subtypeInput('ro.municipalities'));await page.selectQuery(roCity.id);let s=await evalState();assert.equal(s.drawer,false);assert.equal(s.sheet,'peek');assert.equal(s.id,roCity.id);await shot('mobile-peek');for(const [w,h] of [[360,800],[390,600],[430,932]]){await page.viewport(w,h);const v=await bounds(page);within(v.details,v,'peek sheet');assert.ok(v.details.h<=h*.3+1);assert.ok(await page.evaluate("(()=>{const s=document.querySelector('#details-panel').getBoundingClientRect(),r=document.querySelector('#sheet-expand').getBoundingClientRect();return r.top>=s.top&&r.bottom<=s.bottom;})()"),'peek expand clipped');await shot('peek-'+w+'x'+h);}await page.viewport(390,844);await page.click('#sheet-expand');assert.equal((await evalState()).sheet,'expanded');assert.equal(await page.evaluate("document.querySelector('#details-body').hidden"),false);await shot('mobile-expanded');await page.evaluate("document.querySelector('#details-body').scrollTop=100000");assert.ok(await page.evaluate("document.querySelector('#details-body').scrollTop>0"));await page.click('#sheet-expand');await page.click('#mobile-navigation');await openSubtype('ro.municipalities');if(await page.evaluate("document.querySelector('input[data-filter=\"ro.municipalities\"]').checked"))await page.click(subtypeInput('ro.municipalities'));await page.click('#drawer-close');assert.match((await evalState()).hidden,/ascuns/i);await shot('mobile-hidden-geometry');});
 await scenario('mobile tree disclosure selection breadcrumb close and URL',async()=>{await page.click('#mobile-navigation');const selectedId=(await evalState()).id;const summary='.tree-disclosure > summary';await page.click(summary);assert.equal((await evalState()).drawer,true);assert.equal((await evalState()).id,selectedId);await page.click('.tree-select[data-entity-id="osm-r90689"]');await waitFor(()=>page.evaluate("qaApp.selectedEntityId==='osm-r90689'"),'tree root selected');assert.equal((await evalState()).drawer,false);assert.equal((await evalState()).sheet,'peek');await page.click('#sheet-expand');await page.click('.hierarchy-breadcrumb button');await waitFor(()=>page.evaluate('qaApp.atlasMobile.state.sheet===\'peek\''),'breadcrumb peek');await page.click('#details-close');assert.equal((await evalState()).id,null);assert.equal((await evalState()).sheet,'closed');assert.equal((await evalState()).selected,0);assert.equal(new URL((await evalState()).url).searchParams.has('e'),false);});
 await scenario('keyboard skip links actual focus visible accessible names and hidden Tab exclusion',async()=>{await page.evaluate("document.querySelector('#skip-navigation').focus()");await page.key('Enter');assert.equal(await page.evaluate('document.activeElement.id'),'entity-search');await page.key('Escape');assert.equal(await page.evaluate('document.activeElement.id'),'mobile-navigation');await page.key('Tab');assert.notEqual(await page.evaluate("document.activeElement.closest('#atlas-controls')!==null"),true);await page.evaluate("document.querySelector('#skip-map').focus()");assert.equal(await page.evaluate("Math.round(document.querySelector('#skip-map').getBoundingClientRect().top)>=0"),true);await page.key('Enter');assert.equal(await page.evaluate('document.activeElement.id'),'map');const ax=await page.send('Accessibility.getFullAXTree');const names=ax.nodes.filter(n=>!n.ignored).map(n=>n.name?.value);for(const text of ['Hartă teritorială România și Republica Moldova','☰ Entități','Căutare','Filtre','Sari la navigare'])assert.ok(names.includes(text),'AX name '+text);await page.click('#mobile-navigation');await page.key('Tab');await shot('mobile-focus');});

 await scenario('mobile scrolled drawer close and information remain accessible',async()=>{if(!await page.evaluate('qaApp.atlasMobile.state.drawer'))await page.click('#mobile-navigation');await page.evaluate("document.querySelector('#atlas-controls').scrollTop=100000");assert.ok(await page.evaluate("(()=>{const r=document.querySelector('#drawer-close').getBoundingClientRect(),c=document.querySelector('#atlas-controls').getBoundingClientRect();return r.top>=c.top&&r.bottom<=c.bottom&&document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)===document.querySelector('#drawer-close');})()"),'drawer close hidden by scroll');await shot('mobile-scrolled-drawer');await page.click('#info-toggle');assert.equal(await page.evaluate("document.querySelector('#atlas-info-dialog').open"),true);assert.equal((await evalState()).drawer,false);await page.click('#global-provenance summary');await shot('mobile-provenance');await page.click('#info-close');assert.equal(await page.evaluate('document.activeElement.id'),'mobile-navigation');});
 await scenario('delayed real chunk response respects current subtype filters',async()=>{const p=await b.page();await p.viewport(1440,900);const targetBBox=roCity.map.bbox;await p.navigate(base+'?v=1&lat='+((targetBBox[1]+targetBBox[3])/2)+'&lon='+((targetBBox[0]+targetBBox[2])/2)+'&z=6');const chunk='public/geo/actual/chunks/ro/local/'+roCity.hierarchy.parent_catalog_id+'.geojson';await p.send('Fetch.enable',{patterns:[{urlPattern:'*'+chunk,requestStage:'Request'}]});await p.evaluate("(()=>{qaApp.visibleEntityIds.add('"+roCity.id+"');qaApp.refreshGeometryVisibility();void qaApp.selectEntity('"+roCity.id+"',{source:'map',zoom:false}).catch(console.error);})()");const paused=await waitFor(()=>p.paused.find(r=>r.request.url.endsWith(chunk)),'delayed target chunk');if(await p.evaluate("document.querySelector('#filters-panel').hidden"))await p.click('#filters-toggle');await p.evaluate("document.querySelector('input[data-filter=\"ro.municipalities\"]').closest('details').open=true");await p.click(subtypeInput('ro.municipalities'));await p.send('Fetch.continueRequest',{requestId:paused.requestId});await p.send('Fetch.disable');await waitFor(()=>p.evaluate("qaApp.chunkGroups.has('RO_local_"+roCity.hierarchy.parent_catalog_id+"')"),'chunk rendered');assert.equal(await p.evaluate("(()=>{let count=0;qaApp.chunkGroups.get('RO_local_"+roCity.hierarchy.parent_catalog_id+"').eachLayer(g=>g.eachLayer(l=>{if(l.feature?.properties?.entity_id==='"+roCity.id+"')count++;}));return count;})()"),0);assert.equal(p.requests.filter(r=>r.url.endsWith(chunk)).length,1);assert.deepEqual(p.errors,[]);evidence.delayedChunk={path:chunk,requests:1,hiddenSubtypePreserved:true};await p.close();});
 await scenario('console network integrity no errors assets 404 or redundant core fetches',async()=>{await delay(1000);assert.deepEqual(page.errors,[]);const badConsole=page.console.filter(c=>c.type==='error'||c.level==='error');assert.deepEqual(badConsole,[]);assert.deepEqual(page.failures.filter(f=>!f.canceled&&!f.url?.includes('tile.openstreetmap.org')),[]);assert.deepEqual(page.responses.filter(r=>r.status>=400&&!r.url.includes('tile.openstreetmap.org')),[]);for(const suffix of ['actual-entities.json','actual-consolidated-tree.json','actual-release-manifest.json','actual-release-gate.json'])assert.equal(page.requests.filter(r=>r.url.split('?')[0].endsWith(suffix)).length,1,suffix+' refetched');const counts=new Map();for(const r of page.requests.filter(r=>/\/chunks\//.test(r.url)))counts.set(r.url,(counts.get(r.url)||0)+1);evidence.chunkFetchCounts=Object.fromEntries(counts);assert.ok([...counts.values()].every(n=>n===1),'chunk duplicate fetches '+JSON.stringify([...counts].filter(([,n])=>n>1)));});
}finally{evidence.console=page.console;evidence.errors=page.errors;evidence.failures=page.failures;evidence.responses=page.responses;evidence.requests=page.requests;await mkdir(output,{recursive:true});await writeFile(path.join(output,'browser-evidence.json'),JSON.stringify(evidence,null,2));await b.close();}
