import {formatEntityName} from '../../atlas-name-format.mjs';
import {geometryStyleConfig,geometryStyle,entityGeometryStyle,selectedStyle,legendEntries,renderLegend,globalProvenance,renderGlobalProvenance,entityProvenance,entityProvenanceHtml,safeSourceUrl,publishedActualRelease,labelMapControls} from '../../atlas-presentation.mjs';
import {typeLabel} from '../../atlas-search.mjs';
import {createAtlasFilters} from '../../atlas-filters.mjs';
import {createAtlasMobileUi} from '../../atlas-mobile-ui.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createUrlConfig,defaultUrlState,normalizeUrlState,parseUrlState,serializeUrlState,canonicalizeUrlState,sameUrlState,validViewport,createAtlasUrlState,defaultViewport} from '../../atlas-url-state.mjs';
import {createGeometryFilterIndex,geometryParentState} from '../../geometry-taxonomy.mjs';
import {createAtlasTree,ancestorPath} from '../../atlas-tree.mjs';
const data=JSON.parse(readFileSync('public/data/actual-entities.json','utf8')),tree=JSON.parse(readFileSync('public/data/actual-consolidated-tree.json','utf8'));
const entities=new Map(data.entities.map(e=>[e.id,e])),nodes=new Map(tree.nodes.map(n=>[n.id,n])),filterIndex=createGeometryFilterIndex(data.entities);
const config=createUrlConfig({entityById:entities,nodeById:nodes,rootIds:tree.root_ids,filterIndex});
const town=entities.get('osm-r9846233'),commune=data.entities.find(e=>e.jurisdiction==='RO'&&e.representation.inferred_type==='commune');
class Element{
 constructor(tag='div',document){this.tagName=tag.toUpperCase();this.document=document;this.children=[];this.dataset={};this.attributes={};this.listeners={};this.classes=new Set();this.checked=true;this.scrollTop=0;this.clientTop=0;this.clientHeight=100;this._text='';this._html='';this.value='';this.open=false;}
 set className(v){this.classes=new Set(v.split(' '));}get className(){return [...this.classes].join(' ');}
 classList={toggle:(name,on)=>{if(on)this.classes.add(name);else this.classes.delete(name);},contains:name=>this.classes.has(name)};
 set textContent(v){this._text=String(v);this.children=[];}get textContent(){return this._text+this.children.map(c=>c.textContent).join('');}
 set innerHTML(v){this._html=v;this._text='';this.children=[];}get innerHTML(){return this._html;}
 appendChild(c){this.children.push(c);c.parentElement=this;return c;}
 setAttribute(k,v){this.attributes[k]=String(v);}getAttribute(k){return this.attributes[k]??null;}removeAttribute(k){delete this.attributes[k];}
 addEventListener(k,fn){(this.listeners[k]??=[]).push(fn);}focus(){this.document.activeElement=this;}
 async dispatch(k,extra={}){const event={target:this,prevented:false,preventDefault(){this.prevented=true;},stopPropagation(){},...extra};for(const fn of this.listeners[k]??[])await fn(event);return event;}
 async click(){if(this.type==='checkbox'){this.checked=!this.checked;this.indeterminate=false;await this.dispatch('change');}else await this.dispatch('click');}
 contains(el){return el===this||this.descendants().includes(el);}
 descendants(){return this.children.flatMap(c=>[c,...c.descendants()]);}
 querySelectorAll(s){return this.descendants().filter(c=>s==='button'?c.tagName==='BUTTON':s==='nav'?c.tagName==='NAV':s==='details'?c.tagName==='DETAILS':s==='[aria-pressed="true"]'?c.getAttribute('aria-pressed')==='true':s==='.tree-select'?c.classes.has('tree-select'):s==='[role="option"]'?c.getAttribute('role')==='option':false);}
 querySelector(s){return this.querySelectorAll(s)[0]??null;}
 getBoundingClientRect(){return typeof this.rect==='function'?this.rect():this.rect??{top:0,bottom:30,height:30};}
}
function doc(){const elements=new Map(),document={elements,activeElement:null,getElementById(id){if(!elements.has(id)){const el=new Element('div',document);el.id=id;elements.set(id,el);}return elements.get(id);},createElement:tag=>new Element(tag,document),querySelectorAll:()=>[]};return document;}
class Browser{
 constructor(search=''){this.entries=['https://example.test/atlas/index.html'+(search?'?'+search:'')];this.pointer=0;this.pushes=0;this.replaces=0;this.listeners={};this.history={pushState:(_,title,url)=>{this.pushes++;this.entries.splice(this.pointer+1);this.entries.push(new URL(url,this.location.href).href);this.pointer++;},replaceState:(_,title,url)=>{this.replaces++;this.entries[this.pointer]=new URL(url,this.location.href).href;}};}
 get location(){return new URL(this.entries[this.pointer]);}
 addEventListener(name,fn){(this.listeners[name]??=[]).push(fn);}
 async go(delta){this.pointer=Math.max(0,Math.min(this.entries.length-1,this.pointer+delta));for(const fn of this.listeners.popstate??[])await fn({});}
 async visit(search){this.entries[this.pointer]='https://example.test/atlas/index.html'+(search?'?'+search:'');for(const fn of this.listeners.popstate??[])await fn({});}
}

class Media{constructor(matches){this.matches=matches;this.listeners=[];}addEventListener(_,fn){this.listeners.push(fn);}change(matches){this.matches=matches;for(const fn of this.listeners)fn({matches});}}
function shell(document){
 const ids=['atlas-controls','mobile-navigation','drawer-close','drawer-backdrop','details-panel','details-body','sheet-expand','entity-search'];for(const id of ids)document.getElementById(id);
 for(const id of ['entity-search','hierarchy-tree','filter-list','drawer-close','search-results'])document.getElementById('atlas-controls').appendChild(document.getElementById(id));
 for(const id of ['details-body','sheet-expand','details-close'])document.getElementById('details-panel').appendChild(document.getElementById(id));
 document.listeners={};document.addEventListener=(name,fn)=>{(document.listeners[name]??=[]).push(fn);};
 return document;
}

const realManifest=JSON.parse(readFileSync('data/current/actual-release-manifest.json')),realGate=JSON.parse(readFileSync('data/current/actual-release-gate.json')),buildInfo=JSON.parse(readFileSync('public/data/app-build-info.json'));
const county=data.entities.find(e=>e.jurisdiction==='RO'&&e.representation.inferred_type==='county'&&e.statistical),md=entities.get('stat-MD120');
const decode=s=>s.replaceAll('&lt;','<').replaceAll('&gt;','>').replaceAll('&quot;','"').replaceAll('&#39;',"'").replaceAll('&amp;','&');
function populate(parent,html){const stack=[parent];for(const token of html.match(/<!--[\s\S]*?-->|<[^>]+>|[^<]+/g)||[]){if(token.startsWith('<!--')||token.startsWith('<!'))continue;if(token.startsWith('</')){if(stack.length>1)stack.pop();continue;}if(token.startsWith('<')){const match=token.match(/^<([\w-]+)/);if(!match)continue;const el=new Element(match[1],parent.document);if(el.tagName==='INPUT')el.checked=false;for(const a of token.slice(match[0].length).matchAll(/([\w:-]+)(?:="([^"]*)"|='([^']*)'|=([^\s>]+))?/g)){const key=a[1],value=decode(a[2]??a[3]??a[4]??'');el.setAttribute(key,value);if(key==='class')el.className=value;else if(key==='id'||key==='type'||key==='href')el[key]=value;else if(['hidden','checked','disabled'].includes(key))el[key]=true;else if(key==='tabindex')el.tabIndex=Number(value);else if(key.startsWith('data-'))el.dataset[key.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=value;}stack.at(-1).appendChild(el);if(!['INPUT','META','LINK','BR','HR'].includes(el.tagName))stack.push(el);}else{const text=new Element('text',parent.document);text._text=decode(token);stack.at(-1).appendChild(text);}}}
Object.defineProperty(Element.prototype,'innerHTML',{get(){return this._html;},set(value){this._html=value;this._text='';this.children=[];populate(this,value);}});
Element.prototype.blocked=function(){for(let el=this;el;el=el.parentElement)if(el.hidden||el.inert||el.disabled)return true;return false;};
Element.prototype.focus=function(){if(this.blocked())return;const old=this.document.activeElement;if(old!==this)for(const fn of old?.listeners.blur||[])fn({target:old});this.document.activeElement=this;};
Element.prototype.querySelectorAll=function(selector){return this.descendants().filter(el=>selector.split(',').some(s=>{s=s.trim();if(s.startsWith('.'))return el.classes.has(s.slice(1));const match=s.match(/^([\w-]+)?(?:\[([\w-]+)(?:="([^"]*)")?\])?$/);if(!match)return false;return (!match[1]||el.tagName===match[1].toUpperCase())&&(!match[2]||(match[3]===undefined?el.getAttribute(match[2])!==null:el.getAttribute(match[2])===match[3]));}));};
function dom(){const document=doc(),root=new Element('root',document);populate(root,readFileSync('index.html','utf8'));document.root=root;document.getElementById=id=>root.descendants().find(el=>el.id===id)||null;document.querySelector=s=>root.querySelector(s);document.querySelectorAll=s=>root.querySelectorAll(s);document.listeners={};document.addEventListener=(name,fn)=>{(document.listeners[name]??=[]).push(fn);};document.activeElement=root.querySelector('body');return document;}
function uiFixture(){const document=dom(),media=new Media(true),ui=createAtlasMobileUi({document,media,onClear:()=>ui.selection(null)});return {document,media,ui,el:id=>document.getElementById(id)};}
function cssRules(text,media=[],out=[]){text=text.replace(/\/\*[\s\S]*?\*\//g,'');let pos=0;while(pos<text.length){const open=text.indexOf('{',pos);if(open<0)break;const selector=text.slice(pos,open).trim();let depth=1,end=open+1;while(end<text.length&&depth){if(text[end]==='{')depth++;if(text[end]==='}')depth--;end++;}const body=text.slice(open+1,end-1);if(selector.startsWith('@'))cssRules(body,[...media,selector],out);else out.push({selector,media,declarations:Object.fromEntries(body.split(';').filter(v=>v.includes(':')).map(v=>{const split=v.indexOf(':');return [v.slice(0,split).trim(),v.slice(split+1).trim()];}))});pos=end;}return out;}
const rules=cssRules(readFileSync('style.css','utf8')),rule=(selector,media='')=>rules.findLast(r=>r.selector.split(',').map(v=>v.trim()).includes(selector)&&(!media||r.media.some(v=>v.includes(media))));
const tokens=Object.assign({},...rules.filter(r=>r.selector===':root').map(r=>r.declarations));
function contrast(a,b){const luminance=hex=>{const rgb=hex.slice(1).match(/../g).map(v=>parseInt(v,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722;};const [hi,lo]=[luminance(a),luminance(b)].sort((x,y)=>y-x);return (hi+.05)/(lo+.05);}
test('global provenance renders real verified release, snapshot, contract, counts and jurisdictions',()=>{const document=dom(),container=document.getElementById('global-provenance'),model=renderGlobalProvenance({container,document,manifest:realManifest,gate:realGate,index:data,buildInfo});assert.equal(model.publication.tag,'actual-v1.2.0');for(const value of ['actual-v1.2.0',realManifest.snapshot_id,'actual-public-entity-v3','5848','RO / MD','PASS'])assert.ok(container.textContent.includes(value));assert.equal(container.querySelector('a').href,publishedActualRelease.url);assert.equal(container.querySelector('details').open,false);assert.ok(container.querySelector('details').textContent.includes(realManifest.release_fingerprint_sha256));});
test('publication binding fails closed on snapshot or fingerprint drift; stale app metadata stays independent',()=>{for(const field of ['snapshot_id','release_fingerprint_sha256']){const m={...realManifest,[field]:'other'},model=globalProvenance(m,realGate,data,buildInfo);assert.equal(model.publication,null);assert.equal(model.rows[0][1],'Publicare neconfirmată pentru snapshot-ul curent');assert.equal(model.technical.find(r=>r[0].includes('Publicare din'))[1],buildInfo.actual_release_tag);}});
test('coalesced entity has separate official/statistical/cartographic provenance; admin_level only cartographic',()=>{const sections=entityProvenance(county,{typeLabel}),official=sections[0],stat=sections[1],carto=sections[2];assert.deepEqual(sections.map(s=>s.key),['official','statistical','cartographic']);assert.ok(official.rows.some(r=>r[1]==='SIRUTA'));assert.ok(stat.rows.some(r=>r[1]===county.statistical.identity_authority));assert.ok(stat.rows.some(r=>r[1]==='Geometrie administrativă reutilizată'));assert.ok(carto.rows.some(r=>r[0]==='Nivel OSM (metadata cartografică)'&&r[1]===4));assert.ok(!official.rows.some(r=>r[1]===4));});
test('MD120 authority and official code remain distinct from MD121 OSM evidence and separate geometry',()=>{const [legal,stat,carto]=entityProvenance(md);assert.equal(legal.rows.length,0);assert.ok(stat.rows.some(r=>r[1]==='MD120'));assert.ok(stat.rows.some(r=>r[1]==='Limită statistică separată'));assert.ok(stat.rows.some(r=>r[1]===md.statistical.identity_authority));assert.ok(!stat.rows.some(r=>r[1]==='MD121'));assert.ok(carto.rows.some(r=>r[1]==='MD121'));assert.ok(carto.rows.some(r=>r[1]==='Numai evidence OSM; nu stabilește identitatea oficială'));});
test('source links allow only absolute HTTP(S); entity content escapes malicious names and unsafe URLs',()=>{assert.equal(safeSourceUrl('javascript:alert(1)'),null);assert.equal(safeSourceUrl('//example.test'),null);assert.equal(safeSourceUrl('data:text/html,evil'),null);const copy={...county,legal:{...county.legal,name:'<script>evil</script>'},representation:{...county.representation,source_url:'javascript:evil'}};const html=entityProvenanceHtml(copy,{typeLabel});assert.ok(html.includes('&lt;script&gt;evil&lt;/script&gt;'));assert.ok(!html.includes('href="javascript'));});
test('all eight relevant legend entries exist; zero-count unclassified is omitted',()=>{assert.deepEqual(legendEntries(data.entities).map(e=>e.key),['regional','local_uat','sector','component_locality','context','auxiliary','statistical_only','selected']);});
test('legend SVG swatches derive stroke/weight/dash from exact shared map config',()=>{const document=dom(),container=document.getElementById('atlas-legend');renderLegend({container,document,entities:data.entities});for(const item of container.querySelectorAll('li')){const config=item.dataset.legendKey==='selected'?geometryStyle('regional',true):geometryStyle(item.dataset.legendKey),line=item.querySelector('line');assert.equal(line.getAttribute('stroke'),config.color);assert.equal(line.getAttribute('stroke-width'),String(config.weight));assert.equal(line.getAttribute('stroke-dasharray'),config.dashArray||'none');}});
test('legend explains 45 reused and 18 separate roles; has no checkboxes or selection buttons',()=>{const document=dom(),container=document.getElementById('atlas-legend');renderLegend({container,document,entities:data.entities});assert.ok(container.textContent.includes('45 reutilizează'));assert.ok(container.textContent.includes('18 au limite statistice separate'));assert.equal(container.querySelectorAll('input').length,0);assert.equal(container.querySelectorAll('button').length,0);});
test('statistical dash, auxiliary pattern and selected thickness do not rely solely on hue',()=>{assert.equal(geometryStyleConfig.statistical_only.dashArray,'5 4');assert.ok(geometryStyleConfig.auxiliary.dashArray);assert.ok(geometryStyleConfig.component_locality.dashArray);assert.ok(selectedStyle.weight>geometryStyleConfig.context.weight);});
test('landmarks, map accessible name and real skip targets are present in parsed HTML',()=>{const d=dom();assert.equal(d.querySelectorAll('h1').length,1);assert.ok(d.querySelector('main').getAttribute('aria-label'));assert.equal(d.getElementById('details-panel').getAttribute('aria-labelledby'),'details-title');assert.equal(d.getElementById('map').getAttribute('role'),'region');assert.equal(d.getElementById('map').tabIndex,0);for(const id of ['skip-map','skip-navigation'])assert.ok(d.getElementById(d.getElementById(id).href.slice(1)));assert.equal(rule('.skip-link:focus').declarations.transform,'none');});
test('mobile hidden/inert fallback prevents focus entering closed drawer or sheet',()=>{const h=uiFixture(),old=h.document.activeElement;assert.equal(h.el('atlas-controls').hidden,true);assert.equal(h.el('atlas-controls').inert,true);h.el('entity-search').focus();assert.equal(h.document.activeElement,old);h.el('details-close').focus();assert.equal(h.document.activeElement,old);h.ui.openDrawer();assert.equal(h.document.activeElement,h.el('entity-search'));h.ui.closeDrawer();assert.equal(h.document.activeElement,h.el('mobile-navigation'));h.ui.selection(county.id);assert.equal(h.el('details-panel').hidden,false);h.el('sheet-expand').focus();assert.equal(h.document.activeElement,h.el('sheet-expand'));});
test('new mobile target declarations cover two-line tree labels and minimum 44px filter/actions targets',()=>{for(const s of ['.tree-node','.tree-branch>.tree-select','.tree-leaf>.tree-select'])assert.equal(rule(s,'max-width:720px').declarations['min-height'],'52px');for(const s of ['.filter-row','.parent-button','.action-button'])assert.equal(rule(s,'max-width:720px').declarations['min-height'],'44px');assert.equal(rule('.tree-disclosure>.tree-toggle','max-width:720px').declarations.width,'44px');assert.equal(rule('.tree-disclosure>.tree-toggle','max-width:720px').declarations.height,'52px');assert.equal(rule('.mobile-control').declarations['min-height'],'44px');});
test('P3.2 hierarchy controls are accessible and complete labels wrap in a taller viewport',()=>{
 const d=dom();
 for(const id of ['tree-collapse-all','tree-show-roots','tree-expand-depth','tree-expand-apply']){
  const element=d.getElementById(id);assert.ok(element,id);
 }
 assert.equal(d.getElementById('tree-expand-depth').tagName,'SELECT');
 assert.equal(d.getElementById('tree-navigation-status').getAttribute('role'),'status');
 assert.equal(d.getElementById('tree-navigation-status').getAttribute('aria-live'),'polite');
 const containsRule=(selector,key,value,media='')=>rules.some(r=>r.selector.split(',').map(v=>v.trim()).includes(selector)&&r.declarations[key]===value&&(!media||r.media.some(v=>v.includes(media))));
 assert.ok(containsRule('.tree-name','white-space','normal'));
 assert.ok(containsRule('.tree-role','overflow-wrap','anywhere'));
 assert.ok(containsRule('.hierarchy-tree','min-height','clamp(240px,40vh,420px)'));
 assert.ok(containsRule('.tree-branch>.tree-select','position','relative'));
 assert.ok(containsRule('.tree-geometry-hidden>.tree-select','border-inline-end','2px dashed var(--atlas-warning)'));
 assert.equal(rule('.tree-geometry-hidden>.tree-select','forced-colors:active').declarations['border-inline-end'],'2px dashed CanvasText');
});
test('focus-visible coverage includes all interactive classes via a common selector',()=>{const focus=rules.findLast(r=>r.selector===':is(button,a,input,summary,[tabindex]):focus-visible'&&!r.media.length);assert.equal(focus.declarations.outline,'3px solid var(--atlas-focus)');assert.equal(rule('#map:focus-visible').declarations['outline-offset'],'-4px');});
test('readable text, warning, selected row and focus tokens meet contrast thresholds',()=>{const pairs=[['--atlas-text','--atlas-surface'],['--atlas-secondary','--atlas-surface'],['--atlas-text','--atlas-selected']];for(const [fg,bg] of pairs)assert.ok(contrast(tokens[fg],tokens[bg])>=4.5);assert.ok(contrast(tokens['--atlas-warning'],'#f4ede0')>=4.5);assert.ok(contrast(tokens['--atlas-focus'],tokens['--atlas-surface'])>=3);});
test('reduced motion and forced-colors retain outlines/patterns/selected indicators',()=>{assert.equal(rule('.controls','prefers-reduced-motion:reduce').declarations.transition,'none!important');assert.equal(rule('.details','prefers-reduced-motion:reduce').declarations.animation,'none!important');assert.equal(rule('.legend-swatch line','forced-colors:active').declarations.stroke,'CanvasText!important');assert.equal(rule('.tree-select.selected','forced-colors:active').declarations.border,'2px solid Highlight');});
test('Leaflet zoom labels are explicit Romanian accessible names',()=>{const d=dom(),map=d.getElementById('map');for(const cls of ['leaflet-control-zoom-in','leaflet-control-zoom-out']){const b=d.createElement('a');b.className=cls;map.appendChild(b);}labelMapControls(d);assert.equal(d.querySelector('.leaflet-control-zoom-in').getAttribute('aria-label'),'Mărește harta');assert.equal(d.querySelector('.leaflet-control-zoom-out').getAttribute('aria-label'),'Micșorează harta');});
test('native filter labels, statistical names and contextual Toate/Niciuna survive mixed state',()=>{const d=dom(),state={geometryClasses:new Set(config.classes),geometrySubtypes:new Set(config.subtypes),statisticalLevels:new Set([1,2,3]),separateStatisticalGeometry:true},ui=createAtlasFilters({container:d.getElementById('filter-list'),document:d,index:filterIndex,state,onSeparate:()=>{},onChange:()=>{}});state.geometrySubtypes.delete('ro.towns');ui.sync();const parent=ui.parents.get('local_uat');assert.equal(parent.indeterminate,true);assert.equal(parent.parentElement.tagName,'LABEL');assert.equal(ui.levels.get(1).getAttribute('aria-label'),'Nivel statistic 1');assert.ok(d.getElementById('filter-list').querySelectorAll('button').every(b=>b.getAttribute('aria-label').includes(' — ')));});
test('live statuses are scoped to short release/search/copy/geometry messages, not whole details',()=>{const d=dom();assert.equal(d.getElementById('details-panel').getAttribute('aria-live'),null);for(const id of ['search-status','share-status','selection-visibility','geometry-status','actual-release-status']){assert.equal(d.getElementById(id).getAttribute('role'),'status');assert.equal(d.getElementById(id).getAttribute('aria-live'),'polite');}assert.equal(d.getElementById('hierarchy-error').getAttribute('role'),'alert');});
test('real keyboard accessibility integrates provenance, legend, search/tree/filter/url/mobile',async t=>{
 const initial=defaultUrlState(config),browser=new Browser(),document=dom(),media=new Media(true),groups=[],mounted=new Set(),requests=[],fits=[],events=new Map();let viewport={...defaultViewport},failPath=null;browser.matchMedia=()=>media;

 const group=()=>{const g={layers:[],clearLayers(){this.layers=[];},addLayer(l){this.layers.push(l);},hasLayer(l){return this.layers.includes(l);},removeLayer(l){this.layers=this.layers.filter(x=>x!==l);},addTo(target){target.addLayer?.(this);return this;},eachLayer(fn){this.layers.forEach(fn);}};groups.push(g);return g;};
 const emit=name=>{for(const fn of events.get(name)||[])fn();};
 const map={setView([lat,lon],z,options){viewport={lat,lon,z};emit('zoomend');emit('moveend');return this;},addLayer:g=>mounted.add(g),removeLayer:g=>mounted.delete(g),fitBounds(bounds,options){fits.push({bounds,options});viewport={lat:(bounds[0][0]+bounds[1][0])/2,lon:(bounds[0][1]+bounds[1][1])/2,z:12};emit('zoomend');emit('moveend');},wrapLatLng:center=>({...center,lng:((center.lng+180)%360+360)%360-180}),getCenter:()=>({lat:viewport.lat,lng:viewport.lon}),getZoom:()=>viewport.z,on(names,fn){for(const name of names.split(' ')){if(!events.has(name))events.set(name,[]);events.get(name).push(fn);}}};
 const walk=g=>g.layers.flatMap(l=>l.layers?walk(l):[l]),visible=()=>groups.slice(0,2).filter(g=>mounted.has(g)).flatMap(walk);
 const L={map:()=>map,tileLayer:()=>({addTo(){}}),control:{scale:()=>({addTo(){}})},layerGroup:group,geoJSON:(data,options)=>{const g=group();for(const feature of data.features.filter(options.filter)){const layer={feature,handlers:{},bindTooltip(){return this;},on(name,fn){this.handlers[name]=fn;},setStyle(style){this.style=style;}};options.onEachFeature(feature,layer);g.addLayer(layer);}g.addTo=target=>{target.addLayer(g);return g;};return g;}};
 const manifest={...realManifest,public_contract:{...realManifest.public_contract,path:'index',hierarchy:{path:'tree'},geometry_chunks:null,geometry_tiers:Object.fromEntries(['RO','MD'].map(j=>[j,Object.fromEntries(['overview','local','detail'].map(t=>[t,{path:j+'/'+t}]))])),statistical_geometry:{RO:{path:'RO/stat'},MD:{path:'MD/stat'}}}};
 const fetch=async path=>{requests.push(path);if(failPath===path)throw Error('Simulated unavailable geometry');return {ok:true,json:async()=>{if(path==='data/current/actual-release-manifest.json')return manifest;if(path==='data/current/actual-release-gate.json')return realGate;if(path==='public/data/app-build-info.json')return buildInfo;if(path==='index')return data;if(path==='tree')return tree;const [jurisdiction,tier]=path.split('/');return {metadata:tier==='stat'?{contract:'actual-public-statistical-geometry-v1',jurisdiction}:{jurisdiction,tier},features:data.entities.filter(e=>e.jurisdiction===jurisdiction&&(tier==='stat'?e.category==='statistical':e.category!=='statistical'&&e.map.tier===tier)).map(e=>({properties:{entity_id:e.id}}))};}};};
 const previous={document:globalThis.document,L:globalThis.L,fetch:globalThis.fetch,window:globalThis.window},navigatorDescriptor=Object.getOwnPropertyDescriptor(globalThis,'navigator');const copied=[];
 try{
  Object.assign(globalThis,{document,L,fetch,window:browser});Object.defineProperty(globalThis,'navigator',{configurable:true,value:{clipboard:{writeText:async value=>copied.push(value)}}});
  const app=await import('../../app.js?atlas-a11y-tests');await app.frontendReady;assert.ok(app.atlasUrl);const body=document.getElementById('details-body'),treeDOM=document.getElementById('hierarchy-tree'),input=document.getElementById('entity-search'),filtersDOM=document.getElementById('filter-list');
  const selected=id=>{assert.equal(app.selectedEntityId,id);assert.equal(document.getElementById('details-title').textContent,formatEntityName(entities.get(id).display_name));const selected=treeDOM.querySelectorAll('[aria-pressed="true"]');assert.equal(selected.length,1);assert.equal(selected[0].dataset.entityId,id);assert.equal(body.querySelector('nav').querySelectorAll('button').at(-1).dataset.entityId,id);assert.equal(new URLSearchParams(browser.location.search).get('e'),id);};
  const subtype=id=>filtersDOM.descendants().find(e=>e.dataset.kind==='geometry-subtype'&&e.dataset.filter===id);

  const el=id=>document.getElementById(id),ui=app.atlasMobile;
  async function key(name){const event={key:name,preventDefault(){}};for(const fn of document.listeners.keydown??[])fn(event);await input.dispatch('keydown',{key:name});}
  await t.test('app styleFor matches shared tokens for every real entity',()=>{for(const e of data.entities)assert.deepEqual(app.styleFor({properties:{entity_id:e.id}}),entityGeometryStyle(e));});
  await t.test('skip to map focuses actual map; skip to navigation opens drawer and focuses search without URL mutation',async()=>{const href=browser.location.href;await el('skip-map').click();assert.equal(document.activeElement,el('map'));await el('skip-navigation').click();assert.equal(ui.state.drawer,true);assert.equal(document.activeElement,input);assert.equal(browser.location.href,href);});
  await t.test('search retains combobox/listbox/option/current active semantics and polite result status',async()=>{input.value='Victoria';await input.dispatch('input');await key('ArrowDown');assert.equal(input.getAttribute('role'),'combobox');assert.equal(input.getAttribute('aria-expanded'),'true');const active=document.getElementById(input.getAttribute('aria-activedescendant'));assert.equal(active.getAttribute('role'),'option');assert.equal(active.getAttribute('aria-selected'),'true');assert.ok(el('search-status').textContent.includes('rezultate'));input.value='zzzz-imposibil';await input.dispatch('input');assert.equal(el('search-status').textContent,'Nicio entitate găsită.');await key('Escape');assert.equal(ui.state.drawer,true);await key('Escape');assert.equal(ui.state.drawer,false);});
  await t.test('keyboard search→sheet→expand→breadcrumb→clear keeps focus valid and central selection',async()=>{ui.openDrawer();input.value=county.id;await input.dispatch('input');await key('ArrowDown');await key('Enter');selected(county.id);assert.equal(ui.state.sheet,'peek');assert.equal(document.activeElement,el('mobile-navigation'));await el('sheet-expand').click();assert.equal(ui.state.sheet,'expanded');assert.equal(body.hidden,false);assert.deepEqual(body.querySelectorAll('[data-provenance]').map(s=>s.dataset.provenance),['official','statistical','cartographic']);const nav=body.querySelector('nav');assert.equal(nav.getAttribute('aria-label'),'Ierarhie teritorială');assert.equal(nav.querySelector('[aria-current="location"]').dataset.entityId,county.id);const parent=nav.querySelectorAll('button').at(-2);parent.focus();await parent.click();selected(parent.dataset.entityId);assert.ok(!document.activeElement.blocked());el('details-close').focus();await el('details-close').click();assert.equal(app.selectedEntityId,null);assert.equal(ui.state.sheet,'closed');assert.equal(document.activeElement,el('mobile-navigation'));assert.equal(el('selection-visibility').textContent,'');});
  await t.test('tree selected materialization, disclosure separation and reveal on drawer reopen remain intact',async()=>{await app.selectEntity(commune.id,{source:'map'});ui.openDrawer();const button=treeDOM.querySelectorAll('.tree-select').find(b=>b.dataset.entityId===commune.id);assert.equal(button.getAttribute('aria-pressed'),'true');button.rect={top:1200,bottom:1244,height:44};ui.closeDrawer();treeDOM.scrollTop=0;ui.openDrawer();assert.ok(treeDOM.scrollTop>0);const disclosure=treeDOM.querySelector('details'),summary=disclosure.querySelector('summary');assert.equal(summary.tagName,'SUMMARY');assert.equal(disclosure.parentElement.children[0].className,'tree-select');assert.ok(summary.getAttribute('aria-label'));summary.focus();const id=app.selectedEntityId;disclosure.open=!disclosure.open;await disclosure.dispatch('toggle');assert.equal(app.selectedEntityId,id);assert.equal(ui.state.drawer,true);assert.equal(document.activeElement,summary);});
  await t.test('hidden selected geometry announces status in peek without reactivating subtype',async()=>{await subtype('ro.towns').click();await app.selectEntity(town.id,{source:'search'});selected(town.id);assert.equal(ui.state.sheet,'peek');assert.match(el('selection-visibility').textContent,/ascunsă/);assert.equal(el('selection-visibility').hidden,undefined);assert.equal(el('selection-visibility').parentElement,el('details-panel'));assert.equal(app.activeGeometrySubtypes.has('ro.towns'),false);assert.equal(el('selection-visibility').getAttribute('aria-live'),'polite');ui.toggleSheet();assert.equal(body.querySelectorAll('[data-provenance]').length,3);});
  await t.test('MD120 sheet shows official authority, separate geometry and MD121 only evidence',async()=>{await app.selectEntity(md.id,{source:'map'});selected(md.id);ui.toggleSheet();const stat=body.querySelector('[data-provenance="statistical"]'),carto=body.querySelector('[data-provenance="cartographic"]');assert.ok(stat.textContent.includes('MD120'));assert.ok(!stat.textContent.includes('MD121'));assert.ok(carto.textContent.includes('MD121'));assert.ok(carto.textContent.includes('Numai evidence OSM'));assert.ok(stat.textContent.includes('Limită statistică separată'));});
  await t.test('legend/provenance disclosures are read-only and excluded from canonical URL/filter state',async()=>{const href=browser.location.href,filters=[...app.activeGeometrySubtypes],push=browser.pushes;for(const container of [el('atlas-legend'),el('global-provenance')]){const disclosure=container.querySelector('details');disclosure.open=true;await disclosure.dispatch('toggle');}assert.equal(browser.location.href,href);assert.equal(browser.pushes,push);assert.deepEqual([...app.activeGeometrySubtypes],filters);});
  await t.test('provenance accessible on desktop and in mobile drawer/expanded sheet; hidden states normalize',()=>{media.change(false);assert.equal(el('atlas-controls').hidden,false);assert.equal(el('details-panel').hidden,false);assert.ok(el('global-provenance').textContent.includes('actual-v1.2.0'));assert.equal(body.hidden,false);media.change(true);assert.equal(el('atlas-controls').hidden,true);assert.equal(ui.state.sheet,'peek');ui.openDrawer();assert.equal(el('atlas-controls').hidden,false);assert.ok(el('global-provenance').textContent.includes(realManifest.snapshot_id));ui.closeDrawer();ui.toggleSheet();assert.equal(body.hidden,false);});
  await t.test('copy link has name and polite feedback without semantic URL mutation',async()=>{const href=browser.location.href;assert.equal(el('copy-link').textContent,'Copiază link');await el('copy-link').click();assert.equal(el('share-status').textContent,'Link copiat.');assert.equal(el('share-status').getAttribute('aria-live'),'polite');assert.equal(browser.location.href,href);});
  await t.test('geometry failure is distinct and leaves identity, selected tree/breadcrumb and URL intact',async()=>{const saved=app.statisticalFeatureById.get(md.id);app.statisticalFeatureById.delete(md.id);await assert.rejects(app.selectEntity(md.id,{source:'map'}),/Lipsește geometria statistică/);selected(md.id);assert.ok(el('geometry-status').textContent.includes('nu a putut fi încărcată'));assert.equal(el('geometry-status').getAttribute('role'),'status');assert.equal(body.querySelectorAll('[data-provenance]').length,3);app.statisticalFeatureById.set(md.id,saved);});
  await t.test('ACTUAL/P2 identity/counts unchanged',()=>{assert.equal(data.entities.length,5848);assert.equal(tree.nodes.length,5848);assert.equal(data.statistical_role_entity_count,63);assert.equal(data.statistical_only_entity_count,18);assert.equal(realManifest.snapshot_id,publishedActualRelease.snapshot);assert.equal(realManifest.release_fingerprint_sha256,publishedActualRelease.fingerprint);assert.equal(md.statistical.code,'MD120');assert.equal(md.representation.osm_statistical_ref,'MD121');assert.equal(md.representation.osm_ref_is_identity_authority,false);});
 }finally{Object.assign(globalThis,previous);if(navigatorDescriptor)Object.defineProperty(globalThis,'navigator',navigatorDescriptor);else delete globalThis.navigator;}
});

test('missing entity metadata does not invent reconciliation date or fidelity claims',()=>{const e={...county,legal:{...county.legal,reference_year:null},representation:{...county.representation,public_geometry_precision:null}};const rows=entityProvenance(e).flatMap(s=>s.rows).filter(r=>r[1]!=null);assert.ok(!rows.some(r=>r[0]==='An registru'));assert.ok(!rows.some(r=>String(r[1]).includes('fără simplificare')));});
test('release/hierarchy/geometry startup failures communicate independently',async t=>{
 for(const kind of ['release','hierarchy','geometry','metadata'])await t.test(kind,async()=>{
  const initial=defaultUrlState(config),browser=new Browser(),document=dom(),media=new Media(true),groups=[],mounted=new Set(),requests=[],fits=[],events=new Map();let viewport={...defaultViewport},failPath=kind==='hierarchy'?'tree':kind==='geometry'?'RO/overview':null;browser.matchMedia=()=>media;

 const group=()=>{const g={layers:[],clearLayers(){this.layers=[];},addLayer(l){this.layers.push(l);},hasLayer(l){return this.layers.includes(l);},removeLayer(l){this.layers=this.layers.filter(x=>x!==l);},addTo(target){target.addLayer?.(this);return this;},eachLayer(fn){this.layers.forEach(fn);}};groups.push(g);return g;};
 const emit=name=>{for(const fn of events.get(name)||[])fn();};
 const map={setView([lat,lon],z,options){viewport={lat,lon,z};emit('zoomend');emit('moveend');return this;},addLayer:g=>mounted.add(g),removeLayer:g=>mounted.delete(g),fitBounds(bounds,options){fits.push({bounds,options});viewport={lat:(bounds[0][0]+bounds[1][0])/2,lon:(bounds[0][1]+bounds[1][1])/2,z:12};emit('zoomend');emit('moveend');},wrapLatLng:center=>({...center,lng:((center.lng+180)%360+360)%360-180}),getCenter:()=>({lat:viewport.lat,lng:viewport.lon}),getZoom:()=>viewport.z,on(names,fn){for(const name of names.split(' ')){if(!events.has(name))events.set(name,[]);events.get(name).push(fn);}}};
 const walk=g=>g.layers.flatMap(l=>l.layers?walk(l):[l]),visible=()=>groups.slice(0,2).filter(g=>mounted.has(g)).flatMap(walk);
 const L={map:()=>map,tileLayer:()=>({addTo(){}}),control:{scale:()=>({addTo(){}})},layerGroup:group,geoJSON:(data,options)=>{const g=group();for(const feature of data.features.filter(options.filter)){const layer={feature,handlers:{},bindTooltip(){return this;},on(name,fn){this.handlers[name]=fn;},setStyle(style){this.style=style;}};options.onEachFeature(feature,layer);g.addLayer(layer);}g.addTo=target=>{target.addLayer(g);return g;};return g;}};
 const manifest={...realManifest,public_contract:{...realManifest.public_contract,path:'index',hierarchy:{path:'tree'},geometry_chunks:null,geometry_tiers:Object.fromEntries(['RO','MD'].map(j=>[j,Object.fromEntries(['overview','local','detail'].map(t=>[t,{path:j+'/'+t}]))])),statistical_geometry:{RO:{path:'RO/stat'},MD:{path:'MD/stat'}}}};
 const fetch=async path=>{requests.push(path);if(kind==='metadata'&&path==='public/data/app-build-info.json')throw Error('Optional build metadata unavailable');if(failPath===path)throw Error('Simulated unavailable geometry');return {ok:true,json:async()=>{if(path==='data/current/actual-release-manifest.json')return manifest;if(path==='data/current/actual-release-gate.json')return kind==='release'?{...realGate,status:'FAIL'}:realGate;if(path==='public/data/app-build-info.json')return buildInfo;if(path==='index')return data;if(path==='tree')return tree;const [jurisdiction,tier]=path.split('/');return {metadata:tier==='stat'?{contract:'actual-public-statistical-geometry-v1',jurisdiction}:{jurisdiction,tier},features:data.entities.filter(e=>e.jurisdiction===jurisdiction&&(tier==='stat'?e.category==='statistical':e.category!=='statistical'&&e.map.tier===tier)).map(e=>({properties:{entity_id:e.id}}))};}};};
 const previous={document:globalThis.document,L:globalThis.L,fetch:globalThis.fetch,window:globalThis.window},navigatorDescriptor=Object.getOwnPropertyDescriptor(globalThis,'navigator');const copied=[],logged=[],previousError=console.error;console.error=(...args)=>logged.push(args);
 try{
  Object.assign(globalThis,{document,L,fetch,window:browser});Object.defineProperty(globalThis,'navigator',{configurable:true,value:{clipboard:{writeText:async value=>copied.push(value)}}});
  const app=await import('../../app.js?a11y-failure-'+kind);await app.frontendReady;const body=document.getElementById('details-body'),treeDOM=document.getElementById('hierarchy-tree'),input=document.getElementById('entity-search'),filtersDOM=document.getElementById('filter-list');

  if(kind==='metadata'){assert.equal(document.getElementById('actual-release-status').getAttribute('role'),'status');assert.ok(document.getElementById('global-provenance').textContent.includes('actual-v1.2.0'));assert.equal(app.entityById.size,5848);assert.equal(logged.length,0);}
  else assert.ok(logged.length>0);
  if(kind==='release'){assert.equal(document.getElementById('actual-release-status').getAttribute('role'),'alert');assert.ok(document.getElementById('actual-release-status').textContent.includes('nevalidat'));assert.equal(app.entityById.size,0);}
  if(kind==='hierarchy'){assert.equal(document.getElementById('hierarchy-error').getAttribute('role'),'alert');assert.ok(document.getElementById('hierarchy-error').textContent.includes('indisponibilă'));assert.equal(app.entityById.size,5848);assert.ok(document.getElementById('filter-list').querySelectorAll('input').length>0);}
  if(kind==='geometry'){assert.equal(document.getElementById('geometry-load-status').getAttribute('role'),'alert');assert.ok(document.getElementById('geometry-load-status').textContent.includes('Geometria este indisponibilă'));assert.equal(app.hierarchyNodeById.size,5848);assert.equal(app.entityById.size,5848);}
 }finally{console.error=previousError;Object.assign(globalThis,previous);if(navigatorDescriptor)Object.defineProperty(globalThis,'navigator',navigatorDescriptor);else delete globalThis.navigator;}
 });
});
