import {formatEntityName} from '../../atlas-name-format.mjs';
import {createAtlasMobileUi} from '../../atlas-mobile-ui.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createUrlConfig,defaultUrlState,normalizeUrlState,parseUrlState,serializeUrlState,canonicalizeUrlState,sameUrlState,validViewport,createAtlasUrlState,defaultViewport} from '../../atlas-url-state.mjs';
import {createGeometryFilterIndex,geometryParentState} from '../../geometry-taxonomy.mjs';
import {createAtlasTree,ancestorPath} from '../../atlas-tree.mjs';
const data=JSON.parse(readFileSync('public/data/actual-entities.json','utf8')),tree=JSON.parse(readFileSync('public/data/actual-consolidated-tree.json','utf8'));
const entities=new Map(data.entities.map(e=>[e.id,e])),nodes=new Map(tree.nodes.map(n=>[n.id,n])),filterIndex=createGeometryFilterIndex(data.entities);
const config=createUrlConfig({entityById:entities,nodeById:nodes,rootIds:tree.root_ids,filterIndex});
const town=entities.get('osm-r9846233'),commune=data.entities.find(e=>e.jurisdiction==='RO'&&e.representation.inferred_type==='commune');
class Element{
 constructor(tag='div',document){this.tagName=tag.toUpperCase();this.document=document;this.children=[];this.dataset={};this.attributes={};this.listeners={};this.classes=new Set();this.checked=true;this.scrollTop=0;this.clientTop=0;this.clientHeight=100;this._text='';this._html='';this.value='';this.open=false;}
 set className(v){this.classes=new Set(v.split(' '));}get className(){return [...this.classes].join(' ');}
 classList={toggle:(name,on)=>{if(on)this.classes.add(name);else this.classes.delete(name);},contains:name=>this.classes.has(name)};
 set textContent(v){this._text=String(v);this.children=[];}get textContent(){return this._text+this.children.map(c=>c.textContent).join('');}
 set innerHTML(v){this._html=v;this._text='';this.children=[];}get innerHTML(){return this._html;}
 appendChild(c){this.children.push(c);c.parentElement=this;return c;}
 setAttribute(k,v){this.attributes[k]=String(v);}getAttribute(k){return this.attributes[k]??null;}removeAttribute(k){delete this.attributes[k];}
 addEventListener(k,fn){(this.listeners[k]??=[]).push(fn);}focus(){this.document.activeElement=this;}
 async dispatch(k,extra={}){const event={target:this,prevented:false,preventDefault(){this.prevented=true;},stopPropagation(){},...extra};for(const fn of this.listeners[k]??[])await fn(event);return event;}
 async click(){if(this.type==='checkbox'){this.checked=!this.checked;this.indeterminate=false;await this.dispatch('change');}else await this.dispatch('click');}
 contains(el){return el===this||this.descendants().includes(el);}
 descendants(){return this.children.flatMap(c=>[c,...c.descendants()]);}
 querySelectorAll(s){return this.descendants().filter(c=>s==='button'?c.tagName==='BUTTON':s==='nav'?c.tagName==='NAV':s==='details'?c.tagName==='DETAILS':s==='[aria-pressed="true"]'?c.getAttribute('aria-pressed')==='true':s==='.tree-select'?c.classes.has('tree-select'):s==='[role="option"]'?c.getAttribute('role')==='option':false);}
 querySelector(s){return this.querySelectorAll(s)[0]??null;}
 getBoundingClientRect(){return typeof this.rect==='function'?this.rect():this.rect??{top:0,bottom:30,height:30};}
}
function doc(){const elements=new Map(),document={elements,activeElement:null,getElementById(id){if(!elements.has(id)){const el=new Element('div',document);el.id=id;elements.set(id,el);}return elements.get(id);},createElement:tag=>new Element(tag,document),querySelectorAll:()=>[]};return document;}
class Browser{
 constructor(search=''){this.entries=['https://example.test/atlas/index.html'+(search?'?'+search:'')];this.pointer=0;this.pushes=0;this.replaces=0;this.listeners={};this.history={pushState:(_,title,url)=>{this.pushes++;this.entries.splice(this.pointer+1);this.entries.push(new URL(url,this.location.href).href);this.pointer++;},replaceState:(_,title,url)=>{this.replaces++;this.entries[this.pointer]=new URL(url,this.location.href).href;}};}
 get location(){return new URL(this.entries[this.pointer]);}
 addEventListener(name,fn){(this.listeners[name]??=[]).push(fn);}
 async go(delta){this.pointer=Math.max(0,Math.min(this.entries.length-1,this.pointer+delta));for(const fn of this.listeners.popstate??[])await fn({});}
 async visit(search){this.entries[this.pointer]='https://example.test/atlas/index.html'+(search?'?'+search:'');for(const fn of this.listeners.popstate??[])await fn({});}
}

class Media{constructor(matches){this.matches=matches;this.listeners=[];}addEventListener(_,fn){this.listeners.push(fn);}change(matches){this.matches=matches;for(const fn of this.listeners)fn({matches});}}
function shell(document){
 const ids=['atlas-controls','mobile-navigation','drawer-close','drawer-backdrop','details-panel','details-body','sheet-expand','entity-search'];for(const id of ids)document.getElementById(id);
 for(const id of ['entity-search','hierarchy-tree','filter-list','drawer-close','search-results'])document.getElementById('atlas-controls').appendChild(document.getElementById(id));
 for(const id of ['details-body','sheet-expand','details-close'])document.getElementById('details-panel').appendChild(document.getElementById(id));
 document.listeners={};document.addEventListener=(name,fn)=>{(document.listeners[name]??=[]).push(fn);};
 return document;
}
function unit(mobile=true){const document=shell(doc()),media=new Media(mobile);let cleared=0,searchOpen=false;const ui=createAtlasMobileUi({document,media,onClear:()=>{cleared++;ui.selection(null);},isSearchOpen:()=>searchOpen});return {document,media,ui,el:id=>document.getElementById(id),get cleared(){return cleared;},search(value){searchOpen=value;},escape(){const event={key:'Escape',preventDefault(){this.prevented=true;}};for(const fn of document.listeners.keydown)fn(event);return event;}};}
test('desktop keeps controls and hides contextual details until selection; mobile trigger inactive',()=>{const h=unit(false);assert.equal(h.el('mobile-navigation').hidden,true);assert.equal(h.el('atlas-controls').inert,false);assert.equal(h.el('details-panel').inert,true);assert.equal(h.el('details-panel').hidden,true);h.ui.selection('one');assert.equal(h.el('details-panel').inert,false);assert.equal(h.el('details-panel').hidden,false);assert.equal(h.el('details-body').hidden,false);h.ui.selection(null);assert.equal(h.el('details-panel').hidden,true);h.ui.openDrawer();assert.equal(h.ui.state.drawer,false);});
test('mobile defaults to closed drawer and hidden selection sheet',()=>{const h=unit();assert.equal(h.ui.state.drawer,false);assert.equal(h.ui.state.sheet,'closed');assert.equal(h.el('atlas-controls').inert,true);assert.equal(h.el('details-panel').inert,true);assert.equal(h.el('drawer-backdrop').hidden,true);});
test('drawer trigger opens, focuses search and updates ARIA; close returns focus',async()=>{const h=unit();await h.el('mobile-navigation').click();assert.equal(h.el('mobile-navigation').getAttribute('aria-expanded'),'true');assert.equal(h.document.activeElement,h.el('entity-search'));await h.el('drawer-close').click();assert.equal(h.ui.state.drawer,false);assert.equal(h.document.activeElement,h.el('mobile-navigation'));assert.equal(h.el('mobile-navigation').getAttribute('aria-expanded'),'false');});
test('Escape leaves open search to its controller, then closes drawer',()=>{const h=unit();h.ui.openDrawer();h.ui.selection('one');h.search(true);assert.equal(h.escape().prevented,undefined);assert.equal(h.ui.state.drawer,true);h.search(false);assert.equal(h.escape().prevented,true);assert.equal(h.ui.state.drawer,false);assert.equal(h.ui.state.selected,'one');});
test('backdrop closes drawer without clearing entity',async()=>{const h=unit();h.ui.selection('one');h.ui.openDrawer();await h.el('drawer-backdrop').click();assert.equal(h.ui.state.drawer,false);assert.equal(h.ui.state.selected,'one');assert.equal(h.cleared,0);});
test('drawer close/open retains exact tree/filter/input elements and disclosure state',()=>{const h=unit(),tree=h.el('hierarchy-tree'),filter=h.el('filter-list');tree.open=true;filter.open=true;filter.checked=false;h.el('entity-search').value='Iași';h.ui.openDrawer();h.ui.closeDrawer();h.ui.openDrawer();assert.equal(h.el('hierarchy-tree'),tree);assert.equal(tree.open,true);assert.equal(filter.open,true);assert.equal(filter.checked,false);assert.equal(h.el('entity-search').value,'Iași');});
test('search and tree selection close drawer and expose peek without clearing selection',()=>{for(const source of ['search','tree']){const h=unit();h.ui.openDrawer();h.ui.selection('one',{source});assert.deepEqual(h.ui.state,{mobile:true,drawer:false,sheet:'peek',selected:'one'});assert.equal(h.el('details-panel').inert,false);assert.equal(h.el('details-body').hidden,true);}});
test('disclosure UI does not invoke mobile selection or close drawer',()=>{const h=unit();h.ui.openDrawer();h.el('hierarchy-tree').open=true;assert.equal(h.ui.state.drawer,true);assert.equal(h.ui.state.selected,null);});
test('sheet expand and collapse keep selected entity and content; ARIA follows',async()=>{const h=unit();h.ui.selection('one');h.el('details-body').textContent='Identitate';await h.el('sheet-expand').click();assert.equal(h.ui.state.sheet,'expanded');assert.equal(h.el('details-body').hidden,false);assert.equal(h.el('sheet-expand').getAttribute('aria-expanded'),'true');h.el('details-body').focus();await h.el('sheet-expand').click();assert.equal(h.ui.state.sheet,'peek');assert.equal(h.document.activeElement,h.el('sheet-expand'));assert.equal(h.el('details-body').textContent,'Identitate');assert.equal(h.ui.state.selected,'one');});
test('sheet close delegates to central clear exactly once and restores valid focus',()=>{const h=unit();h.ui.selection('one');h.ui.toggleSheet();h.el('details-body').focus();h.ui.clear();assert.equal(h.cleared,1);assert.equal(h.ui.state.sheet,'closed');assert.equal(h.document.activeElement,h.el('mobile-navigation'));});
test('URL restore shows peek and closes drawer; URL clear hides sheet',()=>{const h=unit();h.ui.openDrawer();h.ui.selection('one',{source:'url'});assert.equal(h.ui.state.drawer,false);assert.equal(h.ui.state.sheet,'peek');h.ui.selection(null);assert.equal(h.ui.state.sheet,'closed');});
test('breakpoint transitions keep selection/data and release inert desktop panels',()=>{const h=unit();h.ui.selection('one');h.ui.openDrawer();h.el('filter-list').checked=false;h.media.change(false);assert.equal(h.el('atlas-controls').inert,false);assert.equal(h.el('details-body').hidden,false);assert.equal(h.ui.state.drawer,false);h.media.change(true);assert.equal(h.ui.state.sheet,'peek');assert.equal(h.ui.state.selected,'one');assert.equal(h.el('filter-list').checked,false);assert.equal(h.document.activeElement,h.el('mobile-navigation'));});
test('desktop transition moves focus from hidden mobile trigger to visible search',()=>{const h=unit();h.el('mobile-navigation').focus();h.media.change(false);assert.equal(h.document.activeElement,h.el('entity-search'));assert.equal(h.el('atlas-controls').inert,false);});
test('breadcrumb and map selections show peek without opening controls',()=>{for(const source of ['breadcrumb','map']){const h=unit();h.ui.selection('one',{source});assert.equal(h.ui.state.drawer,false);assert.equal(h.ui.state.sheet,'peek');}});
test('popstate clear cannot leave focus on a hidden sheet header control',()=>{const h=unit();h.ui.selection('one');h.el('sheet-expand').focus();h.ui.selection(null);assert.equal(h.document.activeElement,h.el('mobile-navigation'));assert.equal(h.ui.state.sheet,'closed');});
test('desktop expanded content focus moves to visible expand on mobile transition',()=>{const h=unit(false);h.ui.selection('one');h.el('details-body').focus();h.media.change(true);assert.equal(h.document.activeElement,h.el('sheet-expand'));assert.equal(h.ui.state.sheet,'peek');});
test('real mobile frontend integrates search/tree/filters/history without semantic UI state',async t=>{
 const initial=defaultUrlState(config),browser=new Browser(),document=shell(doc()),media=new Media(true),groups=[],mounted=new Set(),requests=[],fits=[],events=new Map();let viewport={...defaultViewport};browser.matchMedia=query=>{assert.equal(query,'(max-width: 899px)');return media;};

 const group=()=>{const g={layers:[],clearLayers(){this.layers=[];},addLayer(l){this.layers.push(l);},hasLayer(l){return this.layers.includes(l);},removeLayer(l){this.layers=this.layers.filter(x=>x!==l);},addTo(target){target.addLayer?.(this);return this;},eachLayer(fn){this.layers.forEach(fn);}};groups.push(g);return g;};
 const emit=name=>{for(const fn of events.get(name)||[])fn();};
 const map={setView([lat,lon],z,options){viewport={lat,lon,z};emit('zoomend');emit('moveend');return this;},addLayer:g=>mounted.add(g),removeLayer:g=>mounted.delete(g),fitBounds(bounds,options){fits.push({bounds,options});viewport={lat:(bounds[0][0]+bounds[1][0])/2,lon:(bounds[0][1]+bounds[1][1])/2,z:12};emit('zoomend');emit('moveend');},wrapLatLng:center=>({...center,lng:((center.lng+180)%360+360)%360-180}),getCenter:()=>({lat:viewport.lat,lng:viewport.lon}),getZoom:()=>viewport.z,on(names,fn){for(const name of names.split(' ')){if(!events.has(name))events.set(name,[]);events.get(name).push(fn);}}};
 const walk=g=>g.layers.flatMap(l=>l.layers?walk(l):[l]),visible=()=>groups.slice(0,2).filter(g=>mounted.has(g)).flatMap(walk);
 const L={map:()=>map,tileLayer:()=>({addTo(){}}),control:{scale:()=>({addTo(){}})},layerGroup:group,geoJSON:(data,options)=>{const g=group();for(const feature of data.features.filter(options.filter)){const layer={feature,handlers:{},bindTooltip(){return this;},on(name,fn){this.handlers[name]=fn;},setStyle(style){this.style=style;}};options.onEachFeature(feature,layer);g.addLayer(layer);}g.addTo=target=>{target.addLayer(g);return g;};return g;}};
 const manifest={snapshot_id:'fixture',public_contract:{contract:data.contract,path:'index',entity_count:5848,hierarchy:{path:'tree'},geometry_tiers:Object.fromEntries(['RO','MD'].map(j=>[j,Object.fromEntries(['overview','local','detail'].map(t=>[t,{path:j+'/'+t}]))])),statistical_geometry:{RO:{path:'RO/stat'},MD:{path:'MD/stat'}}}};
 const fetch=async path=>{requests.push(path);return {ok:true,json:async()=>{if(path==='data/current/actual-release-manifest.json')return manifest;if(path==='data/current/actual-release-gate.json')return {status:'PASS',snapshot_id:'fixture'};if(path==='public/data/app-build-info.json')return null;if(path==='index')return data;if(path==='tree')return tree;const [jurisdiction,tier]=path.split('/');return {metadata:tier==='stat'?{contract:'actual-public-statistical-geometry-v1',jurisdiction}:{jurisdiction,tier},features:data.entities.filter(e=>e.jurisdiction===jurisdiction&&(tier==='stat'?e.category==='statistical':e.category!=='statistical'&&e.map.tier===tier)).map(e=>({properties:{entity_id:e.id}}))};}};};
 const previous={document:globalThis.document,L:globalThis.L,fetch:globalThis.fetch,window:globalThis.window},navigatorDescriptor=Object.getOwnPropertyDescriptor(globalThis,'navigator');const copied=[];
 try{
  Object.assign(globalThis,{document,L,fetch,window:browser});Object.defineProperty(globalThis,'navigator',{configurable:true,value:{clipboard:{writeText:async value=>copied.push(value)}}});
  const app=await import('../../app.js?atlas-mobile-tests');await app.frontendReady;assert.ok(app.atlasUrl);for(const id of [town.id,commune.id,'stat-MD120'])app.visibleEntityIds.add(id);app.refreshGeometryVisibility();const body=document.getElementById('details-body'),treeDOM=document.getElementById('hierarchy-tree'),input=document.getElementById('entity-search'),filtersDOM=document.getElementById('filter-list');
  const selected=id=>{assert.equal(app.selectedEntityId,id);assert.equal(document.getElementById('details-title').textContent,formatEntityName(entities.get(id).display_name));const selected=treeDOM.querySelectorAll('[aria-pressed="true"]');assert.equal(selected.length,1);assert.equal(selected[0].dataset.entityId,id);assert.equal(body.querySelector('nav').querySelectorAll('button').at(-1).dataset.entityId,id);assert.equal(new URLSearchParams(browser.location.search).get('e'),id);};
  const subtype=id=>filtersDOM.descendants().find(e=>e.dataset.kind==='geometry-subtype'&&e.dataset.filter===id);

  const ui=app.atlasMobile,el=id=>document.getElementById(id);
  async function key(key){const event={key,preventDefault(){this.prevented=true;}};for(const fn of document.listeners.keydown??[])fn(event);await input.dispatch('keydown',{key});}
  await t.test('initial no-selection mobile has inert closed panels and free map',()=>{assert.equal(ui.state.drawer,false);assert.equal(ui.state.sheet,'closed');assert.equal(el('details-panel').inert,true);assert.equal(body.hidden,true);assert.equal(app.selectedEntityId,null);});
  await t.test('search Escape priority retains selection and query',async()=>{ui.openDrawer();input.value='Victoria';await input.dispatch('input');assert.equal(app.atlasSearch.state.open,true);await key('Escape');assert.equal(app.atlasSearch.state.open,false);assert.equal(ui.state.drawer,true);assert.equal(input.value,'Victoria');await key('Escape');assert.equal(ui.state.drawer,false);assert.equal(document.activeElement,el('mobile-navigation'));});
  await t.test('keyboard search uses central selection, closes drawer, shows name/type peek and syncs map/tree/details',async()=>{ui.openDrawer();input.value=commune.id;await input.dispatch('input');assert.equal(input.getAttribute('role'),'combobox');await key('ArrowDown');assert.ok(input.getAttribute('aria-activedescendant'));await key('Enter');selected(commune.id);assert.equal(ui.state.sheet,'peek');assert.equal(ui.state.drawer,false);assert.equal(input.value,formatEntityName(commune.display_name));assert.equal(app.atlasSearch.state.open,false);assert.ok(el('details-summary').textContent);assert.ok(visible().some(l=>l.feature.properties.entity_id===commune.id));});
  await t.test('sheet expand/collapse and drawer actions have zero semantic URL changes',async()=>{const href=browser.location.href,push=browser.pushes,replace=browser.replaces;ui.toggleSheet();assert.equal(body.hidden,false);ui.toggleSheet();ui.openDrawer();ui.closeDrawer();assert.equal(browser.location.href,href);assert.equal(browser.pushes,push);assert.equal(browser.replaces,replace);});
  await t.test('real tree/filter disclosures and parent mixed state survive drawer cycles',async()=>{ui.openDrawer();const parent=treeDOM.querySelectorAll('details')[0];parent.open=!parent.open;await parent.dispatch('toggle');const branchOpen=parent.open,filter=filtersDOM.querySelectorAll('details')[0];filter.open=true;await subtype('ro.towns').click();const mixed=filtersDOM.descendants().find(e=>e.dataset.kind==='geometry-class'&&e.dataset.filter==='local_uat');assert.equal(mixed.indeterminate,true);const url=browser.location.href;ui.closeDrawer();ui.openDrawer();assert.equal(parent.open,branchOpen);assert.equal(filter.open,true);assert.equal(subtype('ro.towns').checked,false);assert.equal(browser.location.href,url);assert.equal(ui.state.drawer,true);});
  await t.test('hidden tree selection closes drawer; filters remain OFF and unique tree/breadcrumb/details selected',async()=>{ui.openDrawer();await app.selectEntity(town.id,{zoom:true,source:'tree'});ui.openDrawer();await treeDOM.querySelectorAll('.tree-select').find(b=>b.dataset.entityId===town.id).click();selected(town.id);assert.equal(ui.state.drawer,false);assert.equal(ui.state.sheet,'peek');assert.equal(app.activeGeometrySubtypes.has('ro.towns'),false);assert.match(el('selection-visibility').textContent,/ascunsă/);assert.ok(!visible().some(l=>l.feature.properties.entity_id===town.id));});
  await t.test('hidden keyboard search also exposes sheet without enabling subtype',async()=>{ui.openDrawer();input.value=town.id;await input.dispatch('input');await key('ArrowDown');await key('Enter');selected(town.id);assert.equal(ui.state.sheet,'peek');assert.equal(ui.state.drawer,false);assert.equal(subtype('ro.towns').checked,false);assert.match(el('selection-visibility').textContent,/ascunsă/);});
  await t.test('breadcrumb central selection keeps sheet present and drawer closed',async()=>{ui.toggleSheet();const buttons=body.querySelector('nav').querySelectorAll('button'),parentButton=buttons.at(-2);await parentButton.click();selected(parentButton.dataset.entityId);assert.equal(ui.state.sheet,'peek');assert.equal(ui.state.drawer,false);});
  await t.test('sheet close clears highlights, breadcrumb and URL; Back/Forward restores peek/closed without new history',async()=>{const id=app.selectedEntityId,push=browser.pushes;await el('details-close').click();assert.equal(app.selectedEntityId,null);assert.equal(ui.state.sheet,'closed');assert.equal(treeDOM.querySelectorAll('[aria-pressed="true"]').length,0);assert.equal(body.querySelector('nav'),null);assert.equal(new URLSearchParams(browser.location.search).has('e'),false);assert.ok(!visible().some(l=>l.style?.color==='#b54a38'));assert.equal(browser.pushes,push+1);await browser.go(-1);selected(id);assert.equal(ui.state.sheet,'peek');assert.equal(ui.state.drawer,false);await browser.go(1);assert.equal(ui.state.sheet,'closed');assert.equal(browser.pushes,push+1);});
  await t.test('statistical-only MD120 uses same sheet and one geometry; breakpoint preserves semantic state',async()=>{await app.selectEntity('stat-MD120',{source:'map'});selected('stat-MD120');assert.equal(ui.state.sheet,'peek');assert.equal(visible().filter(l=>l.feature.properties.entity_id==='stat-MD120').length,1);const href=browser.location.href;media.change(false);assert.equal(el('atlas-controls').inert,false);assert.equal(body.hidden,false);assert.equal(el('mobile-navigation').hidden,true);media.change(true);assert.equal(ui.state.sheet,'peek');assert.equal(app.selectedEntityId,'stat-MD120');assert.equal(browser.location.href,href);});
  await t.test('ACTUAL/P2 public identities and counts remain unchanged',()=>{const manifest=JSON.parse(readFileSync('data/current/actual-release-manifest.json','utf8'));assert.equal(data.entities.length,5848);assert.equal(tree.nodes.length,5848);assert.equal(data.entities.filter(e=>e.roles.includes('statistical')).length,63);assert.equal(data.entities.filter(e=>e.category==='statistical').length,18);assert.equal(manifest.snapshot_id,'actual-a9e5a4ddcb5277ef');assert.equal(manifest.release_fingerprint_sha256,'a9e5a4ddcb5277ef614858c477be42bf1fe32e2ab1ca214ccad94fb9f42a6446');assert.equal(entities.get('stat-MD120').statistical.code,'MD120');assert.equal(entities.get('stat-MD120').representation.osm_statistical_ref,'MD121');assert.equal(entities.get('stat-MD120').representation.osm_ref_is_identity_authority,false);});
 }finally{Object.assign(globalThis,previous);if(navigatorDescriptor)Object.defineProperty(globalThis,'navigator',navigatorDescriptor);else delete globalThis.navigator;}
});
